import org.gradle.api.attributes.java.TargetJvmEnvironment

def agpVersion = providers.gradleProperty("agpVersion")

repositories {
  google()
  mavenCentral()
}

def agpConfiguration = configurations.create("agp") {
  attributes.attribute(
    TargetJvmEnvironment.TARGET_JVM_ENVIRONMENT_ATTRIBUTE,
    objects.named(TargetJvmEnvironment, TargetJvmEnvironment.STANDARD_JVM),
  )
}

dependencies.add("agp", agpVersion.map { "com.android.tools.build:gradle:${it}" })

tasks.register("dumpSources", Copy) {
  inputs.files agpConfiguration
  into(layout.buildDirectory.dir("agp-sources"))

  doFirst {
    delete(layout.buildDirectory.dir("agp-sources"))
  }

  def componentIds = agpConfiguration
    .incoming
    .resolutionResult
    .allDependencies
    .findAll { it.selected.id.group.startsWith("com.android.tools") }
    .collect { it.selected.id }
    .toSet()

  dependencies.createArtifactResolutionQuery()
    .forComponents(componentIds)
    .withArtifacts(JvmLibrary, SourcesArtifact)
    .execute()
    .resolvedComponents
    .collectMany { it.getArtifacts(SourcesArtifact) }
    .findAll { it instanceof ResolvedArtifactResult }
    .each { ResolvedArtifactResult artifact ->
      ModuleComponentIdentifier id = artifact.id.componentIdentifier
      from(zipTree(artifact.file)) {
        into("${id.group}/${id.module}")
      }
    }
}
