// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

/**
 * <pre>
 * Metrics for the emulator windows hypervisor migration.
 * </pre>
 *
 * Protobuf type {@code android_studio.EmulatorWindowsHypervisorMigrationEvent}
 */
public final class EmulatorWindowsHypervisorMigrationEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:android_studio.EmulatorWindowsHypervisorMigrationEvent)
    EmulatorWindowsHypervisorMigrationEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmulatorWindowsHypervisorMigrationEvent.newBuilder() to construct.
  private EmulatorWindowsHypervisorMigrationEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmulatorWindowsHypervisorMigrationEvent() {
    action_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EmulatorWindowsHypervisorMigrationEvent();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorWindowsHypervisorMigrationEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorWindowsHypervisorMigrationEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.class, com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.Builder.class);
  }

  /**
   * Protobuf enum {@code android_studio.EmulatorWindowsHypervisorMigrationEvent.Action}
   */
  public enum Action
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_ACTION = 0;</code>
     */
    UNKNOWN_ACTION(0),
    /**
     * <pre>
     * The banner was shown
     * </pre>
     *
     * <code>BANNER_SHOW = 1;</code>
     */
    BANNER_SHOW(1),
    /**
     * <pre>
     * The WHPX update dialog was shown
     * </pre>
     *
     * <code>WHPX_UPDATE_DIALOG_SHOW = 2;</code>
     */
    WHPX_UPDATE_DIALOG_SHOW(2),
    /**
     * <pre>
     * User accepted the WHPX update suggestion
     * </pre>
     *
     * <code>WHPX_UPDATE_ACCEPTED = 3;</code>
     */
    WHPX_UPDATE_ACCEPTED(3),
    /**
     * <pre>
     * User rejected the WHPX update suggestion
     * </pre>
     *
     * <code>WHPX_UPDATE_REJECTED = 4;</code>
     */
    WHPX_UPDATE_REJECTED(4),
    /**
     * <pre>
     * emulator-check enable-whpx succeeded
     * </pre>
     *
     * <code>ENABLE_WHPX_SUCCESS = 5;</code>
     */
    ENABLE_WHPX_SUCCESS(5),
    /**
     * <pre>
     * emulator-check enable-whpx failed
     * </pre>
     *
     * <code>ENABLE_WHPX_FAILURE = 6;</code>
     */
    ENABLE_WHPX_FAILURE(6),
    ;

    /**
     * <code>UNKNOWN_ACTION = 0;</code>
     */
    public static final int UNKNOWN_ACTION_VALUE = 0;
    /**
     * <pre>
     * The banner was shown
     * </pre>
     *
     * <code>BANNER_SHOW = 1;</code>
     */
    public static final int BANNER_SHOW_VALUE = 1;
    /**
     * <pre>
     * The WHPX update dialog was shown
     * </pre>
     *
     * <code>WHPX_UPDATE_DIALOG_SHOW = 2;</code>
     */
    public static final int WHPX_UPDATE_DIALOG_SHOW_VALUE = 2;
    /**
     * <pre>
     * User accepted the WHPX update suggestion
     * </pre>
     *
     * <code>WHPX_UPDATE_ACCEPTED = 3;</code>
     */
    public static final int WHPX_UPDATE_ACCEPTED_VALUE = 3;
    /**
     * <pre>
     * User rejected the WHPX update suggestion
     * </pre>
     *
     * <code>WHPX_UPDATE_REJECTED = 4;</code>
     */
    public static final int WHPX_UPDATE_REJECTED_VALUE = 4;
    /**
     * <pre>
     * emulator-check enable-whpx succeeded
     * </pre>
     *
     * <code>ENABLE_WHPX_SUCCESS = 5;</code>
     */
    public static final int ENABLE_WHPX_SUCCESS_VALUE = 5;
    /**
     * <pre>
     * emulator-check enable-whpx failed
     * </pre>
     *
     * <code>ENABLE_WHPX_FAILURE = 6;</code>
     */
    public static final int ENABLE_WHPX_FAILURE_VALUE = 6;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Action valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Action forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_ACTION;
        case 1: return BANNER_SHOW;
        case 2: return WHPX_UPDATE_DIALOG_SHOW;
        case 3: return WHPX_UPDATE_ACCEPTED;
        case 4: return WHPX_UPDATE_REJECTED;
        case 5: return ENABLE_WHPX_SUCCESS;
        case 6: return ENABLE_WHPX_FAILURE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Action>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Action> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Action>() {
            public Action findValueByNumber(int number) {
              return Action.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.getDescriptor().getEnumTypes().get(0);
    }

    private static final Action[] VALUES = values();

    public static Action valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Action(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android_studio.EmulatorWindowsHypervisorMigrationEvent.Action)
  }

  private int bitField0_;
  public static final int ACTION_FIELD_NUMBER = 1;
  private int action_ = 0;
  /**
   * <code>optional .android_studio.EmulatorWindowsHypervisorMigrationEvent.Action action = 1;</code>
   * @return Whether the action field is set.
   */
  @java.lang.Override public boolean hasAction() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .android_studio.EmulatorWindowsHypervisorMigrationEvent.Action action = 1;</code>
   * @return The action.
   */
  @java.lang.Override public com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.Action getAction() {
    com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.Action result = com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.Action.forNumber(action_);
    return result == null ? com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.Action.UNKNOWN_ACTION : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, action_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, action_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent)) {
      return super.equals(obj);
    }
    com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent other = (com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent) obj;

    if (hasAction() != other.hasAction()) return false;
    if (hasAction()) {
      if (action_ != other.action_) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAction()) {
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + action_;
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Metrics for the emulator windows hypervisor migration.
   * </pre>
   *
   * Protobuf type {@code android_studio.EmulatorWindowsHypervisorMigrationEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:android_studio.EmulatorWindowsHypervisorMigrationEvent)
      com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorWindowsHypervisorMigrationEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorWindowsHypervisorMigrationEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.class, com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      action_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorWindowsHypervisorMigrationEvent_descriptor;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent build() {
      com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent buildPartial() {
      com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent result = new com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.action_ = action_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent) {
        return mergeFrom((com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent other) {
      if (other == com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.getDefaultInstance()) return this;
      if (other.hasAction()) {
        setAction(other.getAction());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int tmpRaw = input.readEnum();
              com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.Action tmpValue =
                  com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.Action.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(1, tmpRaw);
              } else {
                action_ = tmpRaw;
                bitField0_ |= 0x00000001;
              }
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int action_ = 0;
    /**
     * <code>optional .android_studio.EmulatorWindowsHypervisorMigrationEvent.Action action = 1;</code>
     * @return Whether the action field is set.
     */
    @java.lang.Override public boolean hasAction() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .android_studio.EmulatorWindowsHypervisorMigrationEvent.Action action = 1;</code>
     * @return The action.
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.Action getAction() {
      com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.Action result = com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.Action.forNumber(action_);
      return result == null ? com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.Action.UNKNOWN_ACTION : result;
    }
    /**
     * <code>optional .android_studio.EmulatorWindowsHypervisorMigrationEvent.Action action = 1;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.Action value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      action_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.EmulatorWindowsHypervisorMigrationEvent.Action action = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      bitField0_ = (bitField0_ & ~0x00000001);
      action_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:android_studio.EmulatorWindowsHypervisorMigrationEvent)
  }

  // @@protoc_insertion_point(class_scope:android_studio.EmulatorWindowsHypervisorMigrationEvent)
  private static final com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent();
  }

  public static com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<EmulatorWindowsHypervisorMigrationEvent>
      PARSER = new com.google.protobuf.AbstractParser<EmulatorWindowsHypervisorMigrationEvent>() {
    @java.lang.Override
    public EmulatorWindowsHypervisorMigrationEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EmulatorWindowsHypervisorMigrationEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmulatorWindowsHypervisorMigrationEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

