// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface EmulatorWindowsHypervisorMigrationEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.EmulatorWindowsHypervisorMigrationEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .android_studio.EmulatorWindowsHypervisorMigrationEvent.Action action = 1;</code>
   * @return Whether the action field is set.
   */
  boolean hasAction();
  /**
   * <code>optional .android_studio.EmulatorWindowsHypervisorMigrationEvent.Action action = 1;</code>
   * @return The action.
   */
  com.google.wireless.android.sdk.stats.EmulatorWindowsHypervisorMigrationEvent.Action getAction();
}
