// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface LeakCanaryTaskMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.LeakCanaryTaskMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 task_id = 1;</code>
   * @return Whether the taskId field is set.
   */
  boolean hasTaskId();
  /**
   * <code>optional int64 task_id = 1;</code>
   * @return The taskId.
   */
  long getTaskId();

  /**
   * <code>optional bool auto_inject_popup_shown = 2;</code>
   * @return Whether the autoInjectPopupShown field is set.
   */
  boolean hasAutoInjectPopupShown();
  /**
   * <code>optional bool auto_inject_popup_shown = 2;</code>
   * @return The autoInjectPopupShown.
   */
  boolean getAutoInjectPopupShown();

  /**
   * <code>optional .android_studio.LeakCanaryTaskMetadata.UiAction ui_action = 3;</code>
   * @return Whether the uiAction field is set.
   */
  boolean hasUiAction();
  /**
   * <code>optional .android_studio.LeakCanaryTaskMetadata.UiAction ui_action = 3;</code>
   * @return The uiAction.
   */
  com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.UiAction getUiAction();

  /**
   * <code>optional .android_studio.LeakCanaryTaskMetadata.LeakAnalysis leak_analysis = 4;</code>
   * @return Whether the leakAnalysis field is set.
   */
  boolean hasLeakAnalysis();
  /**
   * <code>optional .android_studio.LeakCanaryTaskMetadata.LeakAnalysis leak_analysis = 4;</code>
   * @return The leakAnalysis.
   */
  com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis getLeakAnalysis();
  /**
   * <code>optional .android_studio.LeakCanaryTaskMetadata.LeakAnalysis leak_analysis = 4;</code>
   */
  com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysisOrBuilder getLeakAnalysisOrBuilder();
}
