// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

/**
 * Protobuf type {@code android_studio.LeakCanaryTaskMetadata}
 */
public final class LeakCanaryTaskMetadata extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:android_studio.LeakCanaryTaskMetadata)
    LeakCanaryTaskMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LeakCanaryTaskMetadata.newBuilder() to construct.
  private LeakCanaryTaskMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LeakCanaryTaskMetadata() {
    uiAction_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LeakCanaryTaskMetadata();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_LeakCanaryTaskMetadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_LeakCanaryTaskMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.class, com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.Builder.class);
  }

  /**
   * Protobuf enum {@code android_studio.LeakCanaryTaskMetadata.UiAction}
   */
  public enum UiAction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_ACTION = 0;</code>
     */
    UNKNOWN_ACTION(0),
    /**
     * <code>FORCE_DUMP_CLICKED = 1;</code>
     */
    FORCE_DUMP_CLICKED(1),
    /**
     * <code>STOP_RECORDING_CLICKED = 2;</code>
     */
    STOP_RECORDING_CLICKED(2),
    /**
     * <code>GO_TO_DECLARATION_CLICKED = 3;</code>
     */
    GO_TO_DECLARATION_CLICKED(3),
    /**
     * <code>COPY_TRACE_CLICKED = 4;</code>
     */
    COPY_TRACE_CLICKED(4),
    /**
     * <code>EXPAND_ALL_NODES_CLICKED = 5;</code>
     */
    EXPAND_ALL_NODES_CLICKED(5),
    /**
     * <code>COLLAPSE_ALL_NODES_CLICKED = 6;</code>
     */
    COLLAPSE_ALL_NODES_CLICKED(6),
    /**
     * <code>NEW_LEAK_SELECTED = 7;</code>
     */
    NEW_LEAK_SELECTED(7),
    /**
     * <code>CANCELLED_DURING_ANALYSIS = 8;</code>
     */
    CANCELLED_DURING_ANALYSIS(8),
    ;

    /**
     * <code>UNKNOWN_ACTION = 0;</code>
     */
    public static final int UNKNOWN_ACTION_VALUE = 0;
    /**
     * <code>FORCE_DUMP_CLICKED = 1;</code>
     */
    public static final int FORCE_DUMP_CLICKED_VALUE = 1;
    /**
     * <code>STOP_RECORDING_CLICKED = 2;</code>
     */
    public static final int STOP_RECORDING_CLICKED_VALUE = 2;
    /**
     * <code>GO_TO_DECLARATION_CLICKED = 3;</code>
     */
    public static final int GO_TO_DECLARATION_CLICKED_VALUE = 3;
    /**
     * <code>COPY_TRACE_CLICKED = 4;</code>
     */
    public static final int COPY_TRACE_CLICKED_VALUE = 4;
    /**
     * <code>EXPAND_ALL_NODES_CLICKED = 5;</code>
     */
    public static final int EXPAND_ALL_NODES_CLICKED_VALUE = 5;
    /**
     * <code>COLLAPSE_ALL_NODES_CLICKED = 6;</code>
     */
    public static final int COLLAPSE_ALL_NODES_CLICKED_VALUE = 6;
    /**
     * <code>NEW_LEAK_SELECTED = 7;</code>
     */
    public static final int NEW_LEAK_SELECTED_VALUE = 7;
    /**
     * <code>CANCELLED_DURING_ANALYSIS = 8;</code>
     */
    public static final int CANCELLED_DURING_ANALYSIS_VALUE = 8;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UiAction valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static UiAction forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_ACTION;
        case 1: return FORCE_DUMP_CLICKED;
        case 2: return STOP_RECORDING_CLICKED;
        case 3: return GO_TO_DECLARATION_CLICKED;
        case 4: return COPY_TRACE_CLICKED;
        case 5: return EXPAND_ALL_NODES_CLICKED;
        case 6: return COLLAPSE_ALL_NODES_CLICKED;
        case 7: return NEW_LEAK_SELECTED;
        case 8: return CANCELLED_DURING_ANALYSIS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UiAction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UiAction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UiAction>() {
            public UiAction findValueByNumber(int number) {
              return UiAction.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.getDescriptor().getEnumTypes().get(0);
    }

    private static final UiAction[] VALUES = values();

    public static UiAction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UiAction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android_studio.LeakCanaryTaskMetadata.UiAction)
  }

  public interface LeakAnalysisOrBuilder extends
      // @@protoc_insertion_point(interface_extends:android_studio.LeakCanaryTaskMetadata.LeakAnalysis)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 retained_objects_count = 1;</code>
     * @return Whether the retainedObjectsCount field is set.
     */
    boolean hasRetainedObjectsCount();
    /**
     * <code>optional int32 retained_objects_count = 1;</code>
     * @return The retainedObjectsCount.
     */
    int getRetainedObjectsCount();

    /**
     * <code>optional int32 occurrences_count = 2;</code>
     * @return Whether the occurrencesCount field is set.
     */
    boolean hasOccurrencesCount();
    /**
     * <code>optional int32 occurrences_count = 2;</code>
     * @return The occurrencesCount.
     */
    int getOccurrencesCount();

    /**
     * <code>optional int64 estimated_memory_leaked_bytes = 3;</code>
     * @return Whether the estimatedMemoryLeakedBytes field is set.
     */
    boolean hasEstimatedMemoryLeakedBytes();
    /**
     * <code>optional int64 estimated_memory_leaked_bytes = 3;</code>
     * @return The estimatedMemoryLeakedBytes.
     */
    long getEstimatedMemoryLeakedBytes();

    /**
     * <code>optional int32 leaking_no_rows = 4;</code>
     * @return Whether the leakingNoRows field is set.
     */
    boolean hasLeakingNoRows();
    /**
     * <code>optional int32 leaking_no_rows = 4;</code>
     * @return The leakingNoRows.
     */
    int getLeakingNoRows();

    /**
     * <code>optional int32 leaking_maybe_rows = 5;</code>
     * @return Whether the leakingMaybeRows field is set.
     */
    boolean hasLeakingMaybeRows();
    /**
     * <code>optional int32 leaking_maybe_rows = 5;</code>
     * @return The leakingMaybeRows.
     */
    int getLeakingMaybeRows();

    /**
     * <code>optional int32 leaking_yes_rows = 6;</code>
     * @return Whether the leakingYesRows field is set.
     */
    boolean hasLeakingYesRows();
    /**
     * <code>optional int32 leaking_yes_rows = 6;</code>
     * @return The leakingYesRows.
     */
    int getLeakingYesRows();

    /**
     * <code>optional int64 heap_dump_analysis_time_ms = 7;</code>
     * @return Whether the heapDumpAnalysisTimeMs field is set.
     */
    boolean hasHeapDumpAnalysisTimeMs();
    /**
     * <code>optional int64 heap_dump_analysis_time_ms = 7;</code>
     * @return The heapDumpAnalysisTimeMs.
     */
    long getHeapDumpAnalysisTimeMs();

    /**
     * <code>optional int64 total_recording_time_ms = 8;</code>
     * @return Whether the totalRecordingTimeMs field is set.
     */
    boolean hasTotalRecordingTimeMs();
    /**
     * <code>optional int64 total_recording_time_ms = 8;</code>
     * @return The totalRecordingTimeMs.
     */
    long getTotalRecordingTimeMs();

    /**
     * <code>optional bool is_library_leak = 9;</code>
     * @return Whether the isLibraryLeak field is set.
     */
    boolean hasIsLibraryLeak();
    /**
     * <code>optional bool is_library_leak = 9;</code>
     * @return The isLibraryLeak.
     */
    boolean getIsLibraryLeak();

    /**
     * <code>optional int64 hprof_file_size_bytes = 10;</code>
     * @return Whether the hprofFileSizeBytes field is set.
     */
    boolean hasHprofFileSizeBytes();
    /**
     * <code>optional int64 hprof_file_size_bytes = 10;</code>
     * @return The hprofFileSizeBytes.
     */
    long getHprofFileSizeBytes();

    /**
     * <code>optional int64 hprof_download_duration_ms = 11;</code>
     * @return Whether the hprofDownloadDurationMs field is set.
     */
    boolean hasHprofDownloadDurationMs();
    /**
     * <code>optional int64 hprof_download_duration_ms = 11;</code>
     * @return The hprofDownloadDurationMs.
     */
    long getHprofDownloadDurationMs();
  }
  /**
   * Protobuf type {@code android_studio.LeakCanaryTaskMetadata.LeakAnalysis}
   */
  public static final class LeakAnalysis extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:android_studio.LeakCanaryTaskMetadata.LeakAnalysis)
      LeakAnalysisOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LeakAnalysis.newBuilder() to construct.
    private LeakAnalysis(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LeakAnalysis() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LeakAnalysis();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_LeakCanaryTaskMetadata_LeakAnalysis_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_LeakCanaryTaskMetadata_LeakAnalysis_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.class, com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.Builder.class);
    }

    private int bitField0_;
    public static final int RETAINED_OBJECTS_COUNT_FIELD_NUMBER = 1;
    private int retainedObjectsCount_ = 0;
    /**
     * <code>optional int32 retained_objects_count = 1;</code>
     * @return Whether the retainedObjectsCount field is set.
     */
    @java.lang.Override
    public boolean hasRetainedObjectsCount() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 retained_objects_count = 1;</code>
     * @return The retainedObjectsCount.
     */
    @java.lang.Override
    public int getRetainedObjectsCount() {
      return retainedObjectsCount_;
    }

    public static final int OCCURRENCES_COUNT_FIELD_NUMBER = 2;
    private int occurrencesCount_ = 0;
    /**
     * <code>optional int32 occurrences_count = 2;</code>
     * @return Whether the occurrencesCount field is set.
     */
    @java.lang.Override
    public boolean hasOccurrencesCount() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 occurrences_count = 2;</code>
     * @return The occurrencesCount.
     */
    @java.lang.Override
    public int getOccurrencesCount() {
      return occurrencesCount_;
    }

    public static final int ESTIMATED_MEMORY_LEAKED_BYTES_FIELD_NUMBER = 3;
    private long estimatedMemoryLeakedBytes_ = 0L;
    /**
     * <code>optional int64 estimated_memory_leaked_bytes = 3;</code>
     * @return Whether the estimatedMemoryLeakedBytes field is set.
     */
    @java.lang.Override
    public boolean hasEstimatedMemoryLeakedBytes() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int64 estimated_memory_leaked_bytes = 3;</code>
     * @return The estimatedMemoryLeakedBytes.
     */
    @java.lang.Override
    public long getEstimatedMemoryLeakedBytes() {
      return estimatedMemoryLeakedBytes_;
    }

    public static final int LEAKING_NO_ROWS_FIELD_NUMBER = 4;
    private int leakingNoRows_ = 0;
    /**
     * <code>optional int32 leaking_no_rows = 4;</code>
     * @return Whether the leakingNoRows field is set.
     */
    @java.lang.Override
    public boolean hasLeakingNoRows() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 leaking_no_rows = 4;</code>
     * @return The leakingNoRows.
     */
    @java.lang.Override
    public int getLeakingNoRows() {
      return leakingNoRows_;
    }

    public static final int LEAKING_MAYBE_ROWS_FIELD_NUMBER = 5;
    private int leakingMaybeRows_ = 0;
    /**
     * <code>optional int32 leaking_maybe_rows = 5;</code>
     * @return Whether the leakingMaybeRows field is set.
     */
    @java.lang.Override
    public boolean hasLeakingMaybeRows() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 leaking_maybe_rows = 5;</code>
     * @return The leakingMaybeRows.
     */
    @java.lang.Override
    public int getLeakingMaybeRows() {
      return leakingMaybeRows_;
    }

    public static final int LEAKING_YES_ROWS_FIELD_NUMBER = 6;
    private int leakingYesRows_ = 0;
    /**
     * <code>optional int32 leaking_yes_rows = 6;</code>
     * @return Whether the leakingYesRows field is set.
     */
    @java.lang.Override
    public boolean hasLeakingYesRows() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int32 leaking_yes_rows = 6;</code>
     * @return The leakingYesRows.
     */
    @java.lang.Override
    public int getLeakingYesRows() {
      return leakingYesRows_;
    }

    public static final int HEAP_DUMP_ANALYSIS_TIME_MS_FIELD_NUMBER = 7;
    private long heapDumpAnalysisTimeMs_ = 0L;
    /**
     * <code>optional int64 heap_dump_analysis_time_ms = 7;</code>
     * @return Whether the heapDumpAnalysisTimeMs field is set.
     */
    @java.lang.Override
    public boolean hasHeapDumpAnalysisTimeMs() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int64 heap_dump_analysis_time_ms = 7;</code>
     * @return The heapDumpAnalysisTimeMs.
     */
    @java.lang.Override
    public long getHeapDumpAnalysisTimeMs() {
      return heapDumpAnalysisTimeMs_;
    }

    public static final int TOTAL_RECORDING_TIME_MS_FIELD_NUMBER = 8;
    private long totalRecordingTimeMs_ = 0L;
    /**
     * <code>optional int64 total_recording_time_ms = 8;</code>
     * @return Whether the totalRecordingTimeMs field is set.
     */
    @java.lang.Override
    public boolean hasTotalRecordingTimeMs() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional int64 total_recording_time_ms = 8;</code>
     * @return The totalRecordingTimeMs.
     */
    @java.lang.Override
    public long getTotalRecordingTimeMs() {
      return totalRecordingTimeMs_;
    }

    public static final int IS_LIBRARY_LEAK_FIELD_NUMBER = 9;
    private boolean isLibraryLeak_ = false;
    /**
     * <code>optional bool is_library_leak = 9;</code>
     * @return Whether the isLibraryLeak field is set.
     */
    @java.lang.Override
    public boolean hasIsLibraryLeak() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional bool is_library_leak = 9;</code>
     * @return The isLibraryLeak.
     */
    @java.lang.Override
    public boolean getIsLibraryLeak() {
      return isLibraryLeak_;
    }

    public static final int HPROF_FILE_SIZE_BYTES_FIELD_NUMBER = 10;
    private long hprofFileSizeBytes_ = 0L;
    /**
     * <code>optional int64 hprof_file_size_bytes = 10;</code>
     * @return Whether the hprofFileSizeBytes field is set.
     */
    @java.lang.Override
    public boolean hasHprofFileSizeBytes() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional int64 hprof_file_size_bytes = 10;</code>
     * @return The hprofFileSizeBytes.
     */
    @java.lang.Override
    public long getHprofFileSizeBytes() {
      return hprofFileSizeBytes_;
    }

    public static final int HPROF_DOWNLOAD_DURATION_MS_FIELD_NUMBER = 11;
    private long hprofDownloadDurationMs_ = 0L;
    /**
     * <code>optional int64 hprof_download_duration_ms = 11;</code>
     * @return Whether the hprofDownloadDurationMs field is set.
     */
    @java.lang.Override
    public boolean hasHprofDownloadDurationMs() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional int64 hprof_download_duration_ms = 11;</code>
     * @return The hprofDownloadDurationMs.
     */
    @java.lang.Override
    public long getHprofDownloadDurationMs() {
      return hprofDownloadDurationMs_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, retainedObjectsCount_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, occurrencesCount_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, estimatedMemoryLeakedBytes_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, leakingNoRows_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, leakingMaybeRows_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, leakingYesRows_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt64(7, heapDumpAnalysisTimeMs_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeInt64(8, totalRecordingTimeMs_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeBool(9, isLibraryLeak_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeInt64(10, hprofFileSizeBytes_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        output.writeInt64(11, hprofDownloadDurationMs_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, retainedObjectsCount_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, occurrencesCount_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, estimatedMemoryLeakedBytes_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, leakingNoRows_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, leakingMaybeRows_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, leakingYesRows_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, heapDumpAnalysisTimeMs_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, totalRecordingTimeMs_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, isLibraryLeak_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, hprofFileSizeBytes_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, hprofDownloadDurationMs_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis)) {
        return super.equals(obj);
      }
      com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis other = (com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis) obj;

      if (hasRetainedObjectsCount() != other.hasRetainedObjectsCount()) return false;
      if (hasRetainedObjectsCount()) {
        if (getRetainedObjectsCount()
            != other.getRetainedObjectsCount()) return false;
      }
      if (hasOccurrencesCount() != other.hasOccurrencesCount()) return false;
      if (hasOccurrencesCount()) {
        if (getOccurrencesCount()
            != other.getOccurrencesCount()) return false;
      }
      if (hasEstimatedMemoryLeakedBytes() != other.hasEstimatedMemoryLeakedBytes()) return false;
      if (hasEstimatedMemoryLeakedBytes()) {
        if (getEstimatedMemoryLeakedBytes()
            != other.getEstimatedMemoryLeakedBytes()) return false;
      }
      if (hasLeakingNoRows() != other.hasLeakingNoRows()) return false;
      if (hasLeakingNoRows()) {
        if (getLeakingNoRows()
            != other.getLeakingNoRows()) return false;
      }
      if (hasLeakingMaybeRows() != other.hasLeakingMaybeRows()) return false;
      if (hasLeakingMaybeRows()) {
        if (getLeakingMaybeRows()
            != other.getLeakingMaybeRows()) return false;
      }
      if (hasLeakingYesRows() != other.hasLeakingYesRows()) return false;
      if (hasLeakingYesRows()) {
        if (getLeakingYesRows()
            != other.getLeakingYesRows()) return false;
      }
      if (hasHeapDumpAnalysisTimeMs() != other.hasHeapDumpAnalysisTimeMs()) return false;
      if (hasHeapDumpAnalysisTimeMs()) {
        if (getHeapDumpAnalysisTimeMs()
            != other.getHeapDumpAnalysisTimeMs()) return false;
      }
      if (hasTotalRecordingTimeMs() != other.hasTotalRecordingTimeMs()) return false;
      if (hasTotalRecordingTimeMs()) {
        if (getTotalRecordingTimeMs()
            != other.getTotalRecordingTimeMs()) return false;
      }
      if (hasIsLibraryLeak() != other.hasIsLibraryLeak()) return false;
      if (hasIsLibraryLeak()) {
        if (getIsLibraryLeak()
            != other.getIsLibraryLeak()) return false;
      }
      if (hasHprofFileSizeBytes() != other.hasHprofFileSizeBytes()) return false;
      if (hasHprofFileSizeBytes()) {
        if (getHprofFileSizeBytes()
            != other.getHprofFileSizeBytes()) return false;
      }
      if (hasHprofDownloadDurationMs() != other.hasHprofDownloadDurationMs()) return false;
      if (hasHprofDownloadDurationMs()) {
        if (getHprofDownloadDurationMs()
            != other.getHprofDownloadDurationMs()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRetainedObjectsCount()) {
        hash = (37 * hash) + RETAINED_OBJECTS_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getRetainedObjectsCount();
      }
      if (hasOccurrencesCount()) {
        hash = (37 * hash) + OCCURRENCES_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getOccurrencesCount();
      }
      if (hasEstimatedMemoryLeakedBytes()) {
        hash = (37 * hash) + ESTIMATED_MEMORY_LEAKED_BYTES_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEstimatedMemoryLeakedBytes());
      }
      if (hasLeakingNoRows()) {
        hash = (37 * hash) + LEAKING_NO_ROWS_FIELD_NUMBER;
        hash = (53 * hash) + getLeakingNoRows();
      }
      if (hasLeakingMaybeRows()) {
        hash = (37 * hash) + LEAKING_MAYBE_ROWS_FIELD_NUMBER;
        hash = (53 * hash) + getLeakingMaybeRows();
      }
      if (hasLeakingYesRows()) {
        hash = (37 * hash) + LEAKING_YES_ROWS_FIELD_NUMBER;
        hash = (53 * hash) + getLeakingYesRows();
      }
      if (hasHeapDumpAnalysisTimeMs()) {
        hash = (37 * hash) + HEAP_DUMP_ANALYSIS_TIME_MS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getHeapDumpAnalysisTimeMs());
      }
      if (hasTotalRecordingTimeMs()) {
        hash = (37 * hash) + TOTAL_RECORDING_TIME_MS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTotalRecordingTimeMs());
      }
      if (hasIsLibraryLeak()) {
        hash = (37 * hash) + IS_LIBRARY_LEAK_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsLibraryLeak());
      }
      if (hasHprofFileSizeBytes()) {
        hash = (37 * hash) + HPROF_FILE_SIZE_BYTES_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getHprofFileSizeBytes());
      }
      if (hasHprofDownloadDurationMs()) {
        hash = (37 * hash) + HPROF_DOWNLOAD_DURATION_MS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getHprofDownloadDurationMs());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code android_studio.LeakCanaryTaskMetadata.LeakAnalysis}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:android_studio.LeakCanaryTaskMetadata.LeakAnalysis)
        com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysisOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_LeakCanaryTaskMetadata_LeakAnalysis_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_LeakCanaryTaskMetadata_LeakAnalysis_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.class, com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.Builder.class);
      }

      // Construct using com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        retainedObjectsCount_ = 0;
        occurrencesCount_ = 0;
        estimatedMemoryLeakedBytes_ = 0L;
        leakingNoRows_ = 0;
        leakingMaybeRows_ = 0;
        leakingYesRows_ = 0;
        heapDumpAnalysisTimeMs_ = 0L;
        totalRecordingTimeMs_ = 0L;
        isLibraryLeak_ = false;
        hprofFileSizeBytes_ = 0L;
        hprofDownloadDurationMs_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_LeakCanaryTaskMetadata_LeakAnalysis_descriptor;
      }

      @java.lang.Override
      public com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis getDefaultInstanceForType() {
        return com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis build() {
        com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis buildPartial() {
        com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis result = new com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.retainedObjectsCount_ = retainedObjectsCount_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.occurrencesCount_ = occurrencesCount_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.estimatedMemoryLeakedBytes_ = estimatedMemoryLeakedBytes_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.leakingNoRows_ = leakingNoRows_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.leakingMaybeRows_ = leakingMaybeRows_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.leakingYesRows_ = leakingYesRows_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.heapDumpAnalysisTimeMs_ = heapDumpAnalysisTimeMs_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.totalRecordingTimeMs_ = totalRecordingTimeMs_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.isLibraryLeak_ = isLibraryLeak_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.hprofFileSizeBytes_ = hprofFileSizeBytes_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.hprofDownloadDurationMs_ = hprofDownloadDurationMs_;
          to_bitField0_ |= 0x00000400;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis) {
          return mergeFrom((com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis other) {
        if (other == com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.getDefaultInstance()) return this;
        if (other.hasRetainedObjectsCount()) {
          setRetainedObjectsCount(other.getRetainedObjectsCount());
        }
        if (other.hasOccurrencesCount()) {
          setOccurrencesCount(other.getOccurrencesCount());
        }
        if (other.hasEstimatedMemoryLeakedBytes()) {
          setEstimatedMemoryLeakedBytes(other.getEstimatedMemoryLeakedBytes());
        }
        if (other.hasLeakingNoRows()) {
          setLeakingNoRows(other.getLeakingNoRows());
        }
        if (other.hasLeakingMaybeRows()) {
          setLeakingMaybeRows(other.getLeakingMaybeRows());
        }
        if (other.hasLeakingYesRows()) {
          setLeakingYesRows(other.getLeakingYesRows());
        }
        if (other.hasHeapDumpAnalysisTimeMs()) {
          setHeapDumpAnalysisTimeMs(other.getHeapDumpAnalysisTimeMs());
        }
        if (other.hasTotalRecordingTimeMs()) {
          setTotalRecordingTimeMs(other.getTotalRecordingTimeMs());
        }
        if (other.hasIsLibraryLeak()) {
          setIsLibraryLeak(other.getIsLibraryLeak());
        }
        if (other.hasHprofFileSizeBytes()) {
          setHprofFileSizeBytes(other.getHprofFileSizeBytes());
        }
        if (other.hasHprofDownloadDurationMs()) {
          setHprofDownloadDurationMs(other.getHprofDownloadDurationMs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                retainedObjectsCount_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                occurrencesCount_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                estimatedMemoryLeakedBytes_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                leakingNoRows_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                leakingMaybeRows_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                leakingYesRows_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                heapDumpAnalysisTimeMs_ = input.readInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                totalRecordingTimeMs_ = input.readInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                isLibraryLeak_ = input.readBool();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 80: {
                hprofFileSizeBytes_ = input.readInt64();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              case 88: {
                hprofDownloadDurationMs_ = input.readInt64();
                bitField0_ |= 0x00000400;
                break;
              } // case 88
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int retainedObjectsCount_ ;
      /**
       * <code>optional int32 retained_objects_count = 1;</code>
       * @return Whether the retainedObjectsCount field is set.
       */
      @java.lang.Override
      public boolean hasRetainedObjectsCount() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 retained_objects_count = 1;</code>
       * @return The retainedObjectsCount.
       */
      @java.lang.Override
      public int getRetainedObjectsCount() {
        return retainedObjectsCount_;
      }
      /**
       * <code>optional int32 retained_objects_count = 1;</code>
       * @param value The retainedObjectsCount to set.
       * @return This builder for chaining.
       */
      public Builder setRetainedObjectsCount(int value) {

        retainedObjectsCount_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 retained_objects_count = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRetainedObjectsCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retainedObjectsCount_ = 0;
        onChanged();
        return this;
      }

      private int occurrencesCount_ ;
      /**
       * <code>optional int32 occurrences_count = 2;</code>
       * @return Whether the occurrencesCount field is set.
       */
      @java.lang.Override
      public boolean hasOccurrencesCount() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 occurrences_count = 2;</code>
       * @return The occurrencesCount.
       */
      @java.lang.Override
      public int getOccurrencesCount() {
        return occurrencesCount_;
      }
      /**
       * <code>optional int32 occurrences_count = 2;</code>
       * @param value The occurrencesCount to set.
       * @return This builder for chaining.
       */
      public Builder setOccurrencesCount(int value) {

        occurrencesCount_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 occurrences_count = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOccurrencesCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        occurrencesCount_ = 0;
        onChanged();
        return this;
      }

      private long estimatedMemoryLeakedBytes_ ;
      /**
       * <code>optional int64 estimated_memory_leaked_bytes = 3;</code>
       * @return Whether the estimatedMemoryLeakedBytes field is set.
       */
      @java.lang.Override
      public boolean hasEstimatedMemoryLeakedBytes() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int64 estimated_memory_leaked_bytes = 3;</code>
       * @return The estimatedMemoryLeakedBytes.
       */
      @java.lang.Override
      public long getEstimatedMemoryLeakedBytes() {
        return estimatedMemoryLeakedBytes_;
      }
      /**
       * <code>optional int64 estimated_memory_leaked_bytes = 3;</code>
       * @param value The estimatedMemoryLeakedBytes to set.
       * @return This builder for chaining.
       */
      public Builder setEstimatedMemoryLeakedBytes(long value) {

        estimatedMemoryLeakedBytes_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 estimated_memory_leaked_bytes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEstimatedMemoryLeakedBytes() {
        bitField0_ = (bitField0_ & ~0x00000004);
        estimatedMemoryLeakedBytes_ = 0L;
        onChanged();
        return this;
      }

      private int leakingNoRows_ ;
      /**
       * <code>optional int32 leaking_no_rows = 4;</code>
       * @return Whether the leakingNoRows field is set.
       */
      @java.lang.Override
      public boolean hasLeakingNoRows() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 leaking_no_rows = 4;</code>
       * @return The leakingNoRows.
       */
      @java.lang.Override
      public int getLeakingNoRows() {
        return leakingNoRows_;
      }
      /**
       * <code>optional int32 leaking_no_rows = 4;</code>
       * @param value The leakingNoRows to set.
       * @return This builder for chaining.
       */
      public Builder setLeakingNoRows(int value) {

        leakingNoRows_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 leaking_no_rows = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeakingNoRows() {
        bitField0_ = (bitField0_ & ~0x00000008);
        leakingNoRows_ = 0;
        onChanged();
        return this;
      }

      private int leakingMaybeRows_ ;
      /**
       * <code>optional int32 leaking_maybe_rows = 5;</code>
       * @return Whether the leakingMaybeRows field is set.
       */
      @java.lang.Override
      public boolean hasLeakingMaybeRows() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 leaking_maybe_rows = 5;</code>
       * @return The leakingMaybeRows.
       */
      @java.lang.Override
      public int getLeakingMaybeRows() {
        return leakingMaybeRows_;
      }
      /**
       * <code>optional int32 leaking_maybe_rows = 5;</code>
       * @param value The leakingMaybeRows to set.
       * @return This builder for chaining.
       */
      public Builder setLeakingMaybeRows(int value) {

        leakingMaybeRows_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 leaking_maybe_rows = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeakingMaybeRows() {
        bitField0_ = (bitField0_ & ~0x00000010);
        leakingMaybeRows_ = 0;
        onChanged();
        return this;
      }

      private int leakingYesRows_ ;
      /**
       * <code>optional int32 leaking_yes_rows = 6;</code>
       * @return Whether the leakingYesRows field is set.
       */
      @java.lang.Override
      public boolean hasLeakingYesRows() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int32 leaking_yes_rows = 6;</code>
       * @return The leakingYesRows.
       */
      @java.lang.Override
      public int getLeakingYesRows() {
        return leakingYesRows_;
      }
      /**
       * <code>optional int32 leaking_yes_rows = 6;</code>
       * @param value The leakingYesRows to set.
       * @return This builder for chaining.
       */
      public Builder setLeakingYesRows(int value) {

        leakingYesRows_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 leaking_yes_rows = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeakingYesRows() {
        bitField0_ = (bitField0_ & ~0x00000020);
        leakingYesRows_ = 0;
        onChanged();
        return this;
      }

      private long heapDumpAnalysisTimeMs_ ;
      /**
       * <code>optional int64 heap_dump_analysis_time_ms = 7;</code>
       * @return Whether the heapDumpAnalysisTimeMs field is set.
       */
      @java.lang.Override
      public boolean hasHeapDumpAnalysisTimeMs() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional int64 heap_dump_analysis_time_ms = 7;</code>
       * @return The heapDumpAnalysisTimeMs.
       */
      @java.lang.Override
      public long getHeapDumpAnalysisTimeMs() {
        return heapDumpAnalysisTimeMs_;
      }
      /**
       * <code>optional int64 heap_dump_analysis_time_ms = 7;</code>
       * @param value The heapDumpAnalysisTimeMs to set.
       * @return This builder for chaining.
       */
      public Builder setHeapDumpAnalysisTimeMs(long value) {

        heapDumpAnalysisTimeMs_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 heap_dump_analysis_time_ms = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeapDumpAnalysisTimeMs() {
        bitField0_ = (bitField0_ & ~0x00000040);
        heapDumpAnalysisTimeMs_ = 0L;
        onChanged();
        return this;
      }

      private long totalRecordingTimeMs_ ;
      /**
       * <code>optional int64 total_recording_time_ms = 8;</code>
       * @return Whether the totalRecordingTimeMs field is set.
       */
      @java.lang.Override
      public boolean hasTotalRecordingTimeMs() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional int64 total_recording_time_ms = 8;</code>
       * @return The totalRecordingTimeMs.
       */
      @java.lang.Override
      public long getTotalRecordingTimeMs() {
        return totalRecordingTimeMs_;
      }
      /**
       * <code>optional int64 total_recording_time_ms = 8;</code>
       * @param value The totalRecordingTimeMs to set.
       * @return This builder for chaining.
       */
      public Builder setTotalRecordingTimeMs(long value) {

        totalRecordingTimeMs_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 total_recording_time_ms = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalRecordingTimeMs() {
        bitField0_ = (bitField0_ & ~0x00000080);
        totalRecordingTimeMs_ = 0L;
        onChanged();
        return this;
      }

      private boolean isLibraryLeak_ ;
      /**
       * <code>optional bool is_library_leak = 9;</code>
       * @return Whether the isLibraryLeak field is set.
       */
      @java.lang.Override
      public boolean hasIsLibraryLeak() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional bool is_library_leak = 9;</code>
       * @return The isLibraryLeak.
       */
      @java.lang.Override
      public boolean getIsLibraryLeak() {
        return isLibraryLeak_;
      }
      /**
       * <code>optional bool is_library_leak = 9;</code>
       * @param value The isLibraryLeak to set.
       * @return This builder for chaining.
       */
      public Builder setIsLibraryLeak(boolean value) {

        isLibraryLeak_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_library_leak = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsLibraryLeak() {
        bitField0_ = (bitField0_ & ~0x00000100);
        isLibraryLeak_ = false;
        onChanged();
        return this;
      }

      private long hprofFileSizeBytes_ ;
      /**
       * <code>optional int64 hprof_file_size_bytes = 10;</code>
       * @return Whether the hprofFileSizeBytes field is set.
       */
      @java.lang.Override
      public boolean hasHprofFileSizeBytes() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional int64 hprof_file_size_bytes = 10;</code>
       * @return The hprofFileSizeBytes.
       */
      @java.lang.Override
      public long getHprofFileSizeBytes() {
        return hprofFileSizeBytes_;
      }
      /**
       * <code>optional int64 hprof_file_size_bytes = 10;</code>
       * @param value The hprofFileSizeBytes to set.
       * @return This builder for chaining.
       */
      public Builder setHprofFileSizeBytes(long value) {

        hprofFileSizeBytes_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 hprof_file_size_bytes = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearHprofFileSizeBytes() {
        bitField0_ = (bitField0_ & ~0x00000200);
        hprofFileSizeBytes_ = 0L;
        onChanged();
        return this;
      }

      private long hprofDownloadDurationMs_ ;
      /**
       * <code>optional int64 hprof_download_duration_ms = 11;</code>
       * @return Whether the hprofDownloadDurationMs field is set.
       */
      @java.lang.Override
      public boolean hasHprofDownloadDurationMs() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>optional int64 hprof_download_duration_ms = 11;</code>
       * @return The hprofDownloadDurationMs.
       */
      @java.lang.Override
      public long getHprofDownloadDurationMs() {
        return hprofDownloadDurationMs_;
      }
      /**
       * <code>optional int64 hprof_download_duration_ms = 11;</code>
       * @param value The hprofDownloadDurationMs to set.
       * @return This builder for chaining.
       */
      public Builder setHprofDownloadDurationMs(long value) {

        hprofDownloadDurationMs_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 hprof_download_duration_ms = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearHprofDownloadDurationMs() {
        bitField0_ = (bitField0_ & ~0x00000400);
        hprofDownloadDurationMs_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:android_studio.LeakCanaryTaskMetadata.LeakAnalysis)
    }

    // @@protoc_insertion_point(class_scope:android_studio.LeakCanaryTaskMetadata.LeakAnalysis)
    private static final com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis();
    }

    public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LeakAnalysis>
        PARSER = new com.google.protobuf.AbstractParser<LeakAnalysis>() {
      @java.lang.Override
      public LeakAnalysis parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LeakAnalysis> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LeakAnalysis> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int TASK_ID_FIELD_NUMBER = 1;
  private long taskId_ = 0L;
  /**
   * <code>optional int64 task_id = 1;</code>
   * @return Whether the taskId field is set.
   */
  @java.lang.Override
  public boolean hasTaskId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int64 task_id = 1;</code>
   * @return The taskId.
   */
  @java.lang.Override
  public long getTaskId() {
    return taskId_;
  }

  public static final int AUTO_INJECT_POPUP_SHOWN_FIELD_NUMBER = 2;
  private boolean autoInjectPopupShown_ = false;
  /**
   * <code>optional bool auto_inject_popup_shown = 2;</code>
   * @return Whether the autoInjectPopupShown field is set.
   */
  @java.lang.Override
  public boolean hasAutoInjectPopupShown() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional bool auto_inject_popup_shown = 2;</code>
   * @return The autoInjectPopupShown.
   */
  @java.lang.Override
  public boolean getAutoInjectPopupShown() {
    return autoInjectPopupShown_;
  }

  public static final int UI_ACTION_FIELD_NUMBER = 3;
  private int uiAction_ = 0;
  /**
   * <code>optional .android_studio.LeakCanaryTaskMetadata.UiAction ui_action = 3;</code>
   * @return Whether the uiAction field is set.
   */
  @java.lang.Override public boolean hasUiAction() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .android_studio.LeakCanaryTaskMetadata.UiAction ui_action = 3;</code>
   * @return The uiAction.
   */
  @java.lang.Override public com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.UiAction getUiAction() {
    com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.UiAction result = com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.UiAction.forNumber(uiAction_);
    return result == null ? com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.UiAction.UNKNOWN_ACTION : result;
  }

  public static final int LEAK_ANALYSIS_FIELD_NUMBER = 4;
  private com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis leakAnalysis_;
  /**
   * <code>optional .android_studio.LeakCanaryTaskMetadata.LeakAnalysis leak_analysis = 4;</code>
   * @return Whether the leakAnalysis field is set.
   */
  @java.lang.Override
  public boolean hasLeakAnalysis() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .android_studio.LeakCanaryTaskMetadata.LeakAnalysis leak_analysis = 4;</code>
   * @return The leakAnalysis.
   */
  @java.lang.Override
  public com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis getLeakAnalysis() {
    return leakAnalysis_ == null ? com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.getDefaultInstance() : leakAnalysis_;
  }
  /**
   * <code>optional .android_studio.LeakCanaryTaskMetadata.LeakAnalysis leak_analysis = 4;</code>
   */
  @java.lang.Override
  public com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysisOrBuilder getLeakAnalysisOrBuilder() {
    return leakAnalysis_ == null ? com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.getDefaultInstance() : leakAnalysis_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, taskId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBool(2, autoInjectPopupShown_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeEnum(3, uiAction_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getLeakAnalysis());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, taskId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, autoInjectPopupShown_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, uiAction_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getLeakAnalysis());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata)) {
      return super.equals(obj);
    }
    com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata other = (com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata) obj;

    if (hasTaskId() != other.hasTaskId()) return false;
    if (hasTaskId()) {
      if (getTaskId()
          != other.getTaskId()) return false;
    }
    if (hasAutoInjectPopupShown() != other.hasAutoInjectPopupShown()) return false;
    if (hasAutoInjectPopupShown()) {
      if (getAutoInjectPopupShown()
          != other.getAutoInjectPopupShown()) return false;
    }
    if (hasUiAction() != other.hasUiAction()) return false;
    if (hasUiAction()) {
      if (uiAction_ != other.uiAction_) return false;
    }
    if (hasLeakAnalysis() != other.hasLeakAnalysis()) return false;
    if (hasLeakAnalysis()) {
      if (!getLeakAnalysis()
          .equals(other.getLeakAnalysis())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTaskId()) {
      hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTaskId());
    }
    if (hasAutoInjectPopupShown()) {
      hash = (37 * hash) + AUTO_INJECT_POPUP_SHOWN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAutoInjectPopupShown());
    }
    if (hasUiAction()) {
      hash = (37 * hash) + UI_ACTION_FIELD_NUMBER;
      hash = (53 * hash) + uiAction_;
    }
    if (hasLeakAnalysis()) {
      hash = (37 * hash) + LEAK_ANALYSIS_FIELD_NUMBER;
      hash = (53 * hash) + getLeakAnalysis().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code android_studio.LeakCanaryTaskMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:android_studio.LeakCanaryTaskMetadata)
      com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_LeakCanaryTaskMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_LeakCanaryTaskMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.class, com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLeakAnalysisFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      taskId_ = 0L;
      autoInjectPopupShown_ = false;
      uiAction_ = 0;
      leakAnalysis_ = null;
      if (leakAnalysisBuilder_ != null) {
        leakAnalysisBuilder_.dispose();
        leakAnalysisBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_LeakCanaryTaskMetadata_descriptor;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata build() {
      com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata buildPartial() {
      com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata result = new com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.taskId_ = taskId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.autoInjectPopupShown_ = autoInjectPopupShown_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.uiAction_ = uiAction_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.leakAnalysis_ = leakAnalysisBuilder_ == null
            ? leakAnalysis_
            : leakAnalysisBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata) {
        return mergeFrom((com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata other) {
      if (other == com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.getDefaultInstance()) return this;
      if (other.hasTaskId()) {
        setTaskId(other.getTaskId());
      }
      if (other.hasAutoInjectPopupShown()) {
        setAutoInjectPopupShown(other.getAutoInjectPopupShown());
      }
      if (other.hasUiAction()) {
        setUiAction(other.getUiAction());
      }
      if (other.hasLeakAnalysis()) {
        mergeLeakAnalysis(other.getLeakAnalysis());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              taskId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              autoInjectPopupShown_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              int tmpRaw = input.readEnum();
              com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.UiAction tmpValue =
                  com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.UiAction.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(3, tmpRaw);
              } else {
                uiAction_ = tmpRaw;
                bitField0_ |= 0x00000004;
              }
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getLeakAnalysisFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long taskId_ ;
    /**
     * <code>optional int64 task_id = 1;</code>
     * @return Whether the taskId field is set.
     */
    @java.lang.Override
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 task_id = 1;</code>
     * @return The taskId.
     */
    @java.lang.Override
    public long getTaskId() {
      return taskId_;
    }
    /**
     * <code>optional int64 task_id = 1;</code>
     * @param value The taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskId(long value) {

      taskId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 task_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      taskId_ = 0L;
      onChanged();
      return this;
    }

    private boolean autoInjectPopupShown_ ;
    /**
     * <code>optional bool auto_inject_popup_shown = 2;</code>
     * @return Whether the autoInjectPopupShown field is set.
     */
    @java.lang.Override
    public boolean hasAutoInjectPopupShown() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bool auto_inject_popup_shown = 2;</code>
     * @return The autoInjectPopupShown.
     */
    @java.lang.Override
    public boolean getAutoInjectPopupShown() {
      return autoInjectPopupShown_;
    }
    /**
     * <code>optional bool auto_inject_popup_shown = 2;</code>
     * @param value The autoInjectPopupShown to set.
     * @return This builder for chaining.
     */
    public Builder setAutoInjectPopupShown(boolean value) {

      autoInjectPopupShown_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool auto_inject_popup_shown = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAutoInjectPopupShown() {
      bitField0_ = (bitField0_ & ~0x00000002);
      autoInjectPopupShown_ = false;
      onChanged();
      return this;
    }

    private int uiAction_ = 0;
    /**
     * <code>optional .android_studio.LeakCanaryTaskMetadata.UiAction ui_action = 3;</code>
     * @return Whether the uiAction field is set.
     */
    @java.lang.Override public boolean hasUiAction() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .android_studio.LeakCanaryTaskMetadata.UiAction ui_action = 3;</code>
     * @return The uiAction.
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.UiAction getUiAction() {
      com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.UiAction result = com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.UiAction.forNumber(uiAction_);
      return result == null ? com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.UiAction.UNKNOWN_ACTION : result;
    }
    /**
     * <code>optional .android_studio.LeakCanaryTaskMetadata.UiAction ui_action = 3;</code>
     * @param value The uiAction to set.
     * @return This builder for chaining.
     */
    public Builder setUiAction(com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.UiAction value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      uiAction_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.LeakCanaryTaskMetadata.UiAction ui_action = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUiAction() {
      bitField0_ = (bitField0_ & ~0x00000004);
      uiAction_ = 0;
      onChanged();
      return this;
    }

    private com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis leakAnalysis_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis, com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.Builder, com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysisOrBuilder> leakAnalysisBuilder_;
    /**
     * <code>optional .android_studio.LeakCanaryTaskMetadata.LeakAnalysis leak_analysis = 4;</code>
     * @return Whether the leakAnalysis field is set.
     */
    public boolean hasLeakAnalysis() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .android_studio.LeakCanaryTaskMetadata.LeakAnalysis leak_analysis = 4;</code>
     * @return The leakAnalysis.
     */
    public com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis getLeakAnalysis() {
      if (leakAnalysisBuilder_ == null) {
        return leakAnalysis_ == null ? com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.getDefaultInstance() : leakAnalysis_;
      } else {
        return leakAnalysisBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .android_studio.LeakCanaryTaskMetadata.LeakAnalysis leak_analysis = 4;</code>
     */
    public Builder setLeakAnalysis(com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis value) {
      if (leakAnalysisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        leakAnalysis_ = value;
      } else {
        leakAnalysisBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.LeakCanaryTaskMetadata.LeakAnalysis leak_analysis = 4;</code>
     */
    public Builder setLeakAnalysis(
        com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.Builder builderForValue) {
      if (leakAnalysisBuilder_ == null) {
        leakAnalysis_ = builderForValue.build();
      } else {
        leakAnalysisBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.LeakCanaryTaskMetadata.LeakAnalysis leak_analysis = 4;</code>
     */
    public Builder mergeLeakAnalysis(com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis value) {
      if (leakAnalysisBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          leakAnalysis_ != null &&
          leakAnalysis_ != com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.getDefaultInstance()) {
          getLeakAnalysisBuilder().mergeFrom(value);
        } else {
          leakAnalysis_ = value;
        }
      } else {
        leakAnalysisBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.LeakCanaryTaskMetadata.LeakAnalysis leak_analysis = 4;</code>
     */
    public Builder clearLeakAnalysis() {
      bitField0_ = (bitField0_ & ~0x00000008);
      leakAnalysis_ = null;
      if (leakAnalysisBuilder_ != null) {
        leakAnalysisBuilder_.dispose();
        leakAnalysisBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.LeakCanaryTaskMetadata.LeakAnalysis leak_analysis = 4;</code>
     */
    public com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.Builder getLeakAnalysisBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getLeakAnalysisFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .android_studio.LeakCanaryTaskMetadata.LeakAnalysis leak_analysis = 4;</code>
     */
    public com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysisOrBuilder getLeakAnalysisOrBuilder() {
      if (leakAnalysisBuilder_ != null) {
        return leakAnalysisBuilder_.getMessageOrBuilder();
      } else {
        return leakAnalysis_ == null ?
            com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.getDefaultInstance() : leakAnalysis_;
      }
    }
    /**
     * <code>optional .android_studio.LeakCanaryTaskMetadata.LeakAnalysis leak_analysis = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis, com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.Builder, com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysisOrBuilder> 
        getLeakAnalysisFieldBuilder() {
      if (leakAnalysisBuilder_ == null) {
        leakAnalysisBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis, com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysis.Builder, com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata.LeakAnalysisOrBuilder>(
                getLeakAnalysis(),
                getParentForChildren(),
                isClean());
        leakAnalysis_ = null;
      }
      return leakAnalysisBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:android_studio.LeakCanaryTaskMetadata)
  }

  // @@protoc_insertion_point(class_scope:android_studio.LeakCanaryTaskMetadata)
  private static final com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata();
  }

  public static com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<LeakCanaryTaskMetadata>
      PARSER = new com.google.protobuf.AbstractParser<LeakCanaryTaskMetadata>() {
    @java.lang.Override
    public LeakCanaryTaskMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LeakCanaryTaskMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LeakCanaryTaskMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.wireless.android.sdk.stats.LeakCanaryTaskMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

