// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface LightbuildSyncRequestedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.LightbuildSyncRequestedEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .android_studio.GradleSyncStats.Trigger trigger = 1;</code>
   * @return Whether the trigger field is set.
   */
  boolean hasTrigger();
  /**
   * <code>optional .android_studio.GradleSyncStats.Trigger trigger = 1;</code>
   * @return The trigger.
   */
  com.google.wireless.android.sdk.stats.GradleSyncStats.Trigger getTrigger();
}
