// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface LogcatUsageEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.LogcatUsageEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The event type
   * </pre>
   *
   * <code>optional .android_studio.LogcatUsageEvent.Type type = 1;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <pre>
   * The event type
   * </pre>
   *
   * <code>optional .android_studio.LogcatUsageEvent.Type type = 1;</code>
   * @return The type.
   */
  com.google.wireless.android.sdk.stats.LogcatUsageEvent.Type getType();

  /**
   * <pre>
   * State of an applied Logcat Format dialog. Set if type is FORMAT_DIALOG
   * </pre>
   *
   * <code>optional .android_studio.LogcatUsageEvent.LogcatFormatDialogEvent format_dialog = 2;</code>
   * @return Whether the formatDialog field is set.
   */
  boolean hasFormatDialog();
  /**
   * <pre>
   * State of an applied Logcat Format dialog. Set if type is FORMAT_DIALOG
   * </pre>
   *
   * <code>optional .android_studio.LogcatUsageEvent.LogcatFormatDialogEvent format_dialog = 2;</code>
   * @return The formatDialog.
   */
  com.google.wireless.android.sdk.stats.LogcatUsageEvent.LogcatFormatDialogEvent getFormatDialog();
  /**
   * <pre>
   * State of an applied Logcat Format dialog. Set if type is FORMAT_DIALOG
   * </pre>
   *
   * <code>optional .android_studio.LogcatUsageEvent.LogcatFormatDialogEvent format_dialog = 2;</code>
   */
  com.google.wireless.android.sdk.stats.LogcatUsageEvent.LogcatFormatDialogEventOrBuilder getFormatDialogOrBuilder();
}
