// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface MemoryUsageReportEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.MemoryUsageReportEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .android_studio.MemoryUsageReportEvent.ComponentMemoryUsage component_stats = 1;</code>
   */
  java.util.List<com.google.wireless.android.sdk.stats.MemoryUsageReportEvent.ComponentMemoryUsage> 
      getComponentStatsList();
  /**
   * <code>repeated .android_studio.MemoryUsageReportEvent.ComponentMemoryUsage component_stats = 1;</code>
   */
  com.google.wireless.android.sdk.stats.MemoryUsageReportEvent.ComponentMemoryUsage getComponentStats(int index);
  /**
   * <code>repeated .android_studio.MemoryUsageReportEvent.ComponentMemoryUsage component_stats = 1;</code>
   */
  int getComponentStatsCount();
  /**
   * <code>repeated .android_studio.MemoryUsageReportEvent.ComponentMemoryUsage component_stats = 1;</code>
   */
  java.util.List<? extends com.google.wireless.android.sdk.stats.MemoryUsageReportEvent.ComponentMemoryUsageOrBuilder> 
      getComponentStatsOrBuilderList();
  /**
   * <code>repeated .android_studio.MemoryUsageReportEvent.ComponentMemoryUsage component_stats = 1;</code>
   */
  com.google.wireless.android.sdk.stats.MemoryUsageReportEvent.ComponentMemoryUsageOrBuilder getComponentStatsOrBuilder(
      int index);

  /**
   * <code>repeated .android_studio.MemoryUsageReportEvent.SharedClusterMemoryUsage shared_stats = 2;</code>
   */
  java.util.List<com.google.wireless.android.sdk.stats.MemoryUsageReportEvent.SharedClusterMemoryUsage> 
      getSharedStatsList();
  /**
   * <code>repeated .android_studio.MemoryUsageReportEvent.SharedClusterMemoryUsage shared_stats = 2;</code>
   */
  com.google.wireless.android.sdk.stats.MemoryUsageReportEvent.SharedClusterMemoryUsage getSharedStats(int index);
  /**
   * <code>repeated .android_studio.MemoryUsageReportEvent.SharedClusterMemoryUsage shared_stats = 2;</code>
   */
  int getSharedStatsCount();
  /**
   * <code>repeated .android_studio.MemoryUsageReportEvent.SharedClusterMemoryUsage shared_stats = 2;</code>
   */
  java.util.List<? extends com.google.wireless.android.sdk.stats.MemoryUsageReportEvent.SharedClusterMemoryUsageOrBuilder> 
      getSharedStatsOrBuilderList();
  /**
   * <code>repeated .android_studio.MemoryUsageReportEvent.SharedClusterMemoryUsage shared_stats = 2;</code>
   */
  com.google.wireless.android.sdk.stats.MemoryUsageReportEvent.SharedClusterMemoryUsageOrBuilder getSharedStatsOrBuilder(
      int index);

  /**
   * <code>repeated .android_studio.MemoryUsageReportEvent.ComponentCategoryMemoryUsage component_category_stats = 3;</code>
   */
  java.util.List<com.google.wireless.android.sdk.stats.MemoryUsageReportEvent.ComponentCategoryMemoryUsage> 
      getComponentCategoryStatsList();
  /**
   * <code>repeated .android_studio.MemoryUsageReportEvent.ComponentCategoryMemoryUsage component_category_stats = 3;</code>
   */
  com.google.wireless.android.sdk.stats.MemoryUsageReportEvent.ComponentCategoryMemoryUsage getComponentCategoryStats(int index);
  /**
   * <code>repeated .android_studio.MemoryUsageReportEvent.ComponentCategoryMemoryUsage component_category_stats = 3;</code>
   */
  int getComponentCategoryStatsCount();
  /**
   * <code>repeated .android_studio.MemoryUsageReportEvent.ComponentCategoryMemoryUsage component_category_stats = 3;</code>
   */
  java.util.List<? extends com.google.wireless.android.sdk.stats.MemoryUsageReportEvent.ComponentCategoryMemoryUsageOrBuilder> 
      getComponentCategoryStatsOrBuilderList();
  /**
   * <code>repeated .android_studio.MemoryUsageReportEvent.ComponentCategoryMemoryUsage component_category_stats = 3;</code>
   */
  com.google.wireless.android.sdk.stats.MemoryUsageReportEvent.ComponentCategoryMemoryUsageOrBuilder getComponentCategoryStatsOrBuilder(
      int index);

  /**
   * <code>optional .android_studio.MemoryUsageReportEvent.MemoryUsageCollectionMetadata metadata = 4;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>optional .android_studio.MemoryUsageReportEvent.MemoryUsageCollectionMetadata metadata = 4;</code>
   * @return The metadata.
   */
  com.google.wireless.android.sdk.stats.MemoryUsageReportEvent.MemoryUsageCollectionMetadata getMetadata();
  /**
   * <code>optional .android_studio.MemoryUsageReportEvent.MemoryUsageCollectionMetadata metadata = 4;</code>
   */
  com.google.wireless.android.sdk.stats.MemoryUsageReportEvent.MemoryUsageCollectionMetadataOrBuilder getMetadataOrBuilder();
}
