// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats_logged_in.proto

package com.google.wireless.android.sdk.stats;

/**
 * Protobuf type {@code android_studio.ModelProviderEventLoggedIn}
 */
public final class ModelProviderEventLoggedIn extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:android_studio.ModelProviderEventLoggedIn)
    ModelProviderEventLoggedInOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ModelProviderEventLoggedIn.newBuilder() to construct.
  private ModelProviderEventLoggedIn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ModelProviderEventLoggedIn() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ModelProviderEventLoggedIn();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStatsLoggedIn.internal_static_android_studio_ModelProviderEventLoggedIn_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStatsLoggedIn.internal_static_android_studio_ModelProviderEventLoggedIn_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.class, com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Builder.class);
  }

  public interface UpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:android_studio.ModelProviderEventLoggedIn.Update)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Total number of local model providers.
     * </pre>
     *
     * <code>optional int32 local_model_providers_count = 1;</code>
     * @return Whether the localModelProvidersCount field is set.
     */
    boolean hasLocalModelProvidersCount();
    /**
     * <pre>
     * Total number of local model providers.
     * </pre>
     *
     * <code>optional int32 local_model_providers_count = 1;</code>
     * @return The localModelProvidersCount.
     */
    int getLocalModelProvidersCount();

    /**
     * <pre>
     * Total number of remote model providers.
     * </pre>
     *
     * <code>optional int32 remote_model_providers_count = 2;</code>
     * @return Whether the remoteModelProvidersCount field is set.
     */
    boolean hasRemoteModelProvidersCount();
    /**
     * <pre>
     * Total number of remote model providers.
     * </pre>
     *
     * <code>optional int32 remote_model_providers_count = 2;</code>
     * @return The remoteModelProvidersCount.
     */
    int getRemoteModelProvidersCount();

    /**
     * <pre>
     * Total number of gemini model providers available for the given API key.
     * </pre>
     *
     * <code>optional int32 gemini_model_providers_count = 3;</code>
     * @return Whether the geminiModelProvidersCount field is set.
     */
    boolean hasGeminiModelProvidersCount();
    /**
     * <pre>
     * Total number of gemini model providers available for the given API key.
     * </pre>
     *
     * <code>optional int32 gemini_model_providers_count = 3;</code>
     * @return The geminiModelProvidersCount.
     */
    int getGeminiModelProvidersCount();
  }
  /**
   * <pre>
   * Updates to the model provider settings: adding/removing model providers.
   * </pre>
   *
   * Protobuf type {@code android_studio.ModelProviderEventLoggedIn.Update}
   */
  public static final class Update extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:android_studio.ModelProviderEventLoggedIn.Update)
      UpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Update.newBuilder() to construct.
    private Update(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Update() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Update();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStatsLoggedIn.internal_static_android_studio_ModelProviderEventLoggedIn_Update_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStatsLoggedIn.internal_static_android_studio_ModelProviderEventLoggedIn_Update_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.class, com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.Builder.class);
    }

    private int bitField0_;
    public static final int LOCAL_MODEL_PROVIDERS_COUNT_FIELD_NUMBER = 1;
    private int localModelProvidersCount_ = 0;
    /**
     * <pre>
     * Total number of local model providers.
     * </pre>
     *
     * <code>optional int32 local_model_providers_count = 1;</code>
     * @return Whether the localModelProvidersCount field is set.
     */
    @java.lang.Override
    public boolean hasLocalModelProvidersCount() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Total number of local model providers.
     * </pre>
     *
     * <code>optional int32 local_model_providers_count = 1;</code>
     * @return The localModelProvidersCount.
     */
    @java.lang.Override
    public int getLocalModelProvidersCount() {
      return localModelProvidersCount_;
    }

    public static final int REMOTE_MODEL_PROVIDERS_COUNT_FIELD_NUMBER = 2;
    private int remoteModelProvidersCount_ = 0;
    /**
     * <pre>
     * Total number of remote model providers.
     * </pre>
     *
     * <code>optional int32 remote_model_providers_count = 2;</code>
     * @return Whether the remoteModelProvidersCount field is set.
     */
    @java.lang.Override
    public boolean hasRemoteModelProvidersCount() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Total number of remote model providers.
     * </pre>
     *
     * <code>optional int32 remote_model_providers_count = 2;</code>
     * @return The remoteModelProvidersCount.
     */
    @java.lang.Override
    public int getRemoteModelProvidersCount() {
      return remoteModelProvidersCount_;
    }

    public static final int GEMINI_MODEL_PROVIDERS_COUNT_FIELD_NUMBER = 3;
    private int geminiModelProvidersCount_ = 0;
    /**
     * <pre>
     * Total number of gemini model providers available for the given API key.
     * </pre>
     *
     * <code>optional int32 gemini_model_providers_count = 3;</code>
     * @return Whether the geminiModelProvidersCount field is set.
     */
    @java.lang.Override
    public boolean hasGeminiModelProvidersCount() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Total number of gemini model providers available for the given API key.
     * </pre>
     *
     * <code>optional int32 gemini_model_providers_count = 3;</code>
     * @return The geminiModelProvidersCount.
     */
    @java.lang.Override
    public int getGeminiModelProvidersCount() {
      return geminiModelProvidersCount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, localModelProvidersCount_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, remoteModelProvidersCount_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, geminiModelProvidersCount_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, localModelProvidersCount_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, remoteModelProvidersCount_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, geminiModelProvidersCount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update)) {
        return super.equals(obj);
      }
      com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update other = (com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update) obj;

      if (hasLocalModelProvidersCount() != other.hasLocalModelProvidersCount()) return false;
      if (hasLocalModelProvidersCount()) {
        if (getLocalModelProvidersCount()
            != other.getLocalModelProvidersCount()) return false;
      }
      if (hasRemoteModelProvidersCount() != other.hasRemoteModelProvidersCount()) return false;
      if (hasRemoteModelProvidersCount()) {
        if (getRemoteModelProvidersCount()
            != other.getRemoteModelProvidersCount()) return false;
      }
      if (hasGeminiModelProvidersCount() != other.hasGeminiModelProvidersCount()) return false;
      if (hasGeminiModelProvidersCount()) {
        if (getGeminiModelProvidersCount()
            != other.getGeminiModelProvidersCount()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLocalModelProvidersCount()) {
        hash = (37 * hash) + LOCAL_MODEL_PROVIDERS_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getLocalModelProvidersCount();
      }
      if (hasRemoteModelProvidersCount()) {
        hash = (37 * hash) + REMOTE_MODEL_PROVIDERS_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getRemoteModelProvidersCount();
      }
      if (hasGeminiModelProvidersCount()) {
        hash = (37 * hash) + GEMINI_MODEL_PROVIDERS_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getGeminiModelProvidersCount();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Updates to the model provider settings: adding/removing model providers.
     * </pre>
     *
     * Protobuf type {@code android_studio.ModelProviderEventLoggedIn.Update}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:android_studio.ModelProviderEventLoggedIn.Update)
        com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.UpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.wireless.android.sdk.stats.AndroidStudioStatsLoggedIn.internal_static_android_studio_ModelProviderEventLoggedIn_Update_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.wireless.android.sdk.stats.AndroidStudioStatsLoggedIn.internal_static_android_studio_ModelProviderEventLoggedIn_Update_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.class, com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.Builder.class);
      }

      // Construct using com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        localModelProvidersCount_ = 0;
        remoteModelProvidersCount_ = 0;
        geminiModelProvidersCount_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.wireless.android.sdk.stats.AndroidStudioStatsLoggedIn.internal_static_android_studio_ModelProviderEventLoggedIn_Update_descriptor;
      }

      @java.lang.Override
      public com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update getDefaultInstanceForType() {
        return com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update build() {
        com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update buildPartial() {
        com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update result = new com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.localModelProvidersCount_ = localModelProvidersCount_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.remoteModelProvidersCount_ = remoteModelProvidersCount_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.geminiModelProvidersCount_ = geminiModelProvidersCount_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update) {
          return mergeFrom((com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update other) {
        if (other == com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.getDefaultInstance()) return this;
        if (other.hasLocalModelProvidersCount()) {
          setLocalModelProvidersCount(other.getLocalModelProvidersCount());
        }
        if (other.hasRemoteModelProvidersCount()) {
          setRemoteModelProvidersCount(other.getRemoteModelProvidersCount());
        }
        if (other.hasGeminiModelProvidersCount()) {
          setGeminiModelProvidersCount(other.getGeminiModelProvidersCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                localModelProvidersCount_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                remoteModelProvidersCount_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                geminiModelProvidersCount_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int localModelProvidersCount_ ;
      /**
       * <pre>
       * Total number of local model providers.
       * </pre>
       *
       * <code>optional int32 local_model_providers_count = 1;</code>
       * @return Whether the localModelProvidersCount field is set.
       */
      @java.lang.Override
      public boolean hasLocalModelProvidersCount() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Total number of local model providers.
       * </pre>
       *
       * <code>optional int32 local_model_providers_count = 1;</code>
       * @return The localModelProvidersCount.
       */
      @java.lang.Override
      public int getLocalModelProvidersCount() {
        return localModelProvidersCount_;
      }
      /**
       * <pre>
       * Total number of local model providers.
       * </pre>
       *
       * <code>optional int32 local_model_providers_count = 1;</code>
       * @param value The localModelProvidersCount to set.
       * @return This builder for chaining.
       */
      public Builder setLocalModelProvidersCount(int value) {

        localModelProvidersCount_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Total number of local model providers.
       * </pre>
       *
       * <code>optional int32 local_model_providers_count = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocalModelProvidersCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        localModelProvidersCount_ = 0;
        onChanged();
        return this;
      }

      private int remoteModelProvidersCount_ ;
      /**
       * <pre>
       * Total number of remote model providers.
       * </pre>
       *
       * <code>optional int32 remote_model_providers_count = 2;</code>
       * @return Whether the remoteModelProvidersCount field is set.
       */
      @java.lang.Override
      public boolean hasRemoteModelProvidersCount() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Total number of remote model providers.
       * </pre>
       *
       * <code>optional int32 remote_model_providers_count = 2;</code>
       * @return The remoteModelProvidersCount.
       */
      @java.lang.Override
      public int getRemoteModelProvidersCount() {
        return remoteModelProvidersCount_;
      }
      /**
       * <pre>
       * Total number of remote model providers.
       * </pre>
       *
       * <code>optional int32 remote_model_providers_count = 2;</code>
       * @param value The remoteModelProvidersCount to set.
       * @return This builder for chaining.
       */
      public Builder setRemoteModelProvidersCount(int value) {

        remoteModelProvidersCount_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Total number of remote model providers.
       * </pre>
       *
       * <code>optional int32 remote_model_providers_count = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemoteModelProvidersCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        remoteModelProvidersCount_ = 0;
        onChanged();
        return this;
      }

      private int geminiModelProvidersCount_ ;
      /**
       * <pre>
       * Total number of gemini model providers available for the given API key.
       * </pre>
       *
       * <code>optional int32 gemini_model_providers_count = 3;</code>
       * @return Whether the geminiModelProvidersCount field is set.
       */
      @java.lang.Override
      public boolean hasGeminiModelProvidersCount() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * Total number of gemini model providers available for the given API key.
       * </pre>
       *
       * <code>optional int32 gemini_model_providers_count = 3;</code>
       * @return The geminiModelProvidersCount.
       */
      @java.lang.Override
      public int getGeminiModelProvidersCount() {
        return geminiModelProvidersCount_;
      }
      /**
       * <pre>
       * Total number of gemini model providers available for the given API key.
       * </pre>
       *
       * <code>optional int32 gemini_model_providers_count = 3;</code>
       * @param value The geminiModelProvidersCount to set.
       * @return This builder for chaining.
       */
      public Builder setGeminiModelProvidersCount(int value) {

        geminiModelProvidersCount_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Total number of gemini model providers available for the given API key.
       * </pre>
       *
       * <code>optional int32 gemini_model_providers_count = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGeminiModelProvidersCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        geminiModelProvidersCount_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:android_studio.ModelProviderEventLoggedIn.Update)
    }

    // @@protoc_insertion_point(class_scope:android_studio.ModelProviderEventLoggedIn.Update)
    private static final com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update();
    }

    public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Update>
        PARSER = new com.google.protobuf.AbstractParser<Update>() {
      @java.lang.Override
      public Update parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Update> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Update> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int UPDATE_FIELD_NUMBER = 1;
  private com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update update_;
  /**
   * <code>optional .android_studio.ModelProviderEventLoggedIn.Update update = 1;</code>
   * @return Whether the update field is set.
   */
  @java.lang.Override
  public boolean hasUpdate() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .android_studio.ModelProviderEventLoggedIn.Update update = 1;</code>
   * @return The update.
   */
  @java.lang.Override
  public com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update getUpdate() {
    return update_ == null ? com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.getDefaultInstance() : update_;
  }
  /**
   * <code>optional .android_studio.ModelProviderEventLoggedIn.Update update = 1;</code>
   */
  @java.lang.Override
  public com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.UpdateOrBuilder getUpdateOrBuilder() {
    return update_ == null ? com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.getDefaultInstance() : update_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getUpdate());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUpdate());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn)) {
      return super.equals(obj);
    }
    com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn other = (com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn) obj;

    if (hasUpdate() != other.hasUpdate()) return false;
    if (hasUpdate()) {
      if (!getUpdate()
          .equals(other.getUpdate())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUpdate()) {
      hash = (37 * hash) + UPDATE_FIELD_NUMBER;
      hash = (53 * hash) + getUpdate().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code android_studio.ModelProviderEventLoggedIn}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:android_studio.ModelProviderEventLoggedIn)
      com.google.wireless.android.sdk.stats.ModelProviderEventLoggedInOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStatsLoggedIn.internal_static_android_studio_ModelProviderEventLoggedIn_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStatsLoggedIn.internal_static_android_studio_ModelProviderEventLoggedIn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.class, com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUpdateFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      update_ = null;
      if (updateBuilder_ != null) {
        updateBuilder_.dispose();
        updateBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStatsLoggedIn.internal_static_android_studio_ModelProviderEventLoggedIn_descriptor;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn build() {
      com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn buildPartial() {
      com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn result = new com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.update_ = updateBuilder_ == null
            ? update_
            : updateBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn) {
        return mergeFrom((com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn other) {
      if (other == com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.getDefaultInstance()) return this;
      if (other.hasUpdate()) {
        mergeUpdate(other.getUpdate());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getUpdateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update update_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update, com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.Builder, com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.UpdateOrBuilder> updateBuilder_;
    /**
     * <code>optional .android_studio.ModelProviderEventLoggedIn.Update update = 1;</code>
     * @return Whether the update field is set.
     */
    public boolean hasUpdate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .android_studio.ModelProviderEventLoggedIn.Update update = 1;</code>
     * @return The update.
     */
    public com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update getUpdate() {
      if (updateBuilder_ == null) {
        return update_ == null ? com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.getDefaultInstance() : update_;
      } else {
        return updateBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .android_studio.ModelProviderEventLoggedIn.Update update = 1;</code>
     */
    public Builder setUpdate(com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update value) {
      if (updateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        update_ = value;
      } else {
        updateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.ModelProviderEventLoggedIn.Update update = 1;</code>
     */
    public Builder setUpdate(
        com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.Builder builderForValue) {
      if (updateBuilder_ == null) {
        update_ = builderForValue.build();
      } else {
        updateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.ModelProviderEventLoggedIn.Update update = 1;</code>
     */
    public Builder mergeUpdate(com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update value) {
      if (updateBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          update_ != null &&
          update_ != com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.getDefaultInstance()) {
          getUpdateBuilder().mergeFrom(value);
        } else {
          update_ = value;
        }
      } else {
        updateBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.ModelProviderEventLoggedIn.Update update = 1;</code>
     */
    public Builder clearUpdate() {
      bitField0_ = (bitField0_ & ~0x00000001);
      update_ = null;
      if (updateBuilder_ != null) {
        updateBuilder_.dispose();
        updateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.ModelProviderEventLoggedIn.Update update = 1;</code>
     */
    public com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.Builder getUpdateBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getUpdateFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .android_studio.ModelProviderEventLoggedIn.Update update = 1;</code>
     */
    public com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.UpdateOrBuilder getUpdateOrBuilder() {
      if (updateBuilder_ != null) {
        return updateBuilder_.getMessageOrBuilder();
      } else {
        return update_ == null ?
            com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.getDefaultInstance() : update_;
      }
    }
    /**
     * <code>optional .android_studio.ModelProviderEventLoggedIn.Update update = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update, com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.Builder, com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.UpdateOrBuilder> 
        getUpdateFieldBuilder() {
      if (updateBuilder_ == null) {
        updateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update, com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update.Builder, com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.UpdateOrBuilder>(
                getUpdate(),
                getParentForChildren(),
                isClean());
        update_ = null;
      }
      return updateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:android_studio.ModelProviderEventLoggedIn)
  }

  // @@protoc_insertion_point(class_scope:android_studio.ModelProviderEventLoggedIn)
  private static final com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn();
  }

  public static com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ModelProviderEventLoggedIn>
      PARSER = new com.google.protobuf.AbstractParser<ModelProviderEventLoggedIn>() {
    @java.lang.Override
    public ModelProviderEventLoggedIn parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ModelProviderEventLoggedIn> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ModelProviderEventLoggedIn> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

