// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats_logged_in.proto

package com.google.wireless.android.sdk.stats;

public interface ModelProviderEventLoggedInOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.ModelProviderEventLoggedIn)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .android_studio.ModelProviderEventLoggedIn.Update update = 1;</code>
   * @return Whether the update field is set.
   */
  boolean hasUpdate();
  /**
   * <code>optional .android_studio.ModelProviderEventLoggedIn.Update update = 1;</code>
   * @return The update.
   */
  com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.Update getUpdate();
  /**
   * <code>optional .android_studio.ModelProviderEventLoggedIn.Update update = 1;</code>
   */
  com.google.wireless.android.sdk.stats.ModelProviderEventLoggedIn.UpdateOrBuilder getUpdateOrBuilder();
}
