// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

/**
 * <pre>
 **
 * Logged whenever the Visual Diff Viewer is displayed or when the user
 * switches between comparison modes (tabs).
 * </pre>
 *
 * Protobuf type {@code android_studio.RenderDiffViewerEvent}
 */
public final class RenderDiffViewerEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:android_studio.RenderDiffViewerEvent)
    RenderDiffViewerEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RenderDiffViewerEvent.newBuilder() to construct.
  private RenderDiffViewerEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RenderDiffViewerEvent() {
    viewMode_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RenderDiffViewerEvent();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_RenderDiffViewerEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_RenderDiffViewerEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.class, com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.Builder.class);
  }

  /**
   * Protobuf enum {@code android_studio.RenderDiffViewerEvent.ViewMode}
   */
  public enum ViewMode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_VIEW_MODE = 0;</code>
     */
    UNKNOWN_VIEW_MODE(0),
    /**
     * <pre>
     * Default single image view
     * </pre>
     *
     * <code>NEW = 1;</code>
     */
    NEW(1),
    /**
     * <pre>
     * View only the historical snapshot
     * </pre>
     *
     * <code>PREVIOUS = 2;</code>
     */
    PREVIOUS(2),
    /**
     * <pre>
     * Side-by-side comparison
     * </pre>
     *
     * <code>SPLIT_VIEW = 3;</code>
     */
    SPLIT_VIEW(3),
    /**
     * <pre>
     * Pixel-level heatmap (Heatmap)
     * </pre>
     *
     * <code>DIFF_VIEW = 4;</code>
     */
    DIFF_VIEW(4),
    ;

    /**
     * <code>UNKNOWN_VIEW_MODE = 0;</code>
     */
    public static final int UNKNOWN_VIEW_MODE_VALUE = 0;
    /**
     * <pre>
     * Default single image view
     * </pre>
     *
     * <code>NEW = 1;</code>
     */
    public static final int NEW_VALUE = 1;
    /**
     * <pre>
     * View only the historical snapshot
     * </pre>
     *
     * <code>PREVIOUS = 2;</code>
     */
    public static final int PREVIOUS_VALUE = 2;
    /**
     * <pre>
     * Side-by-side comparison
     * </pre>
     *
     * <code>SPLIT_VIEW = 3;</code>
     */
    public static final int SPLIT_VIEW_VALUE = 3;
    /**
     * <pre>
     * Pixel-level heatmap (Heatmap)
     * </pre>
     *
     * <code>DIFF_VIEW = 4;</code>
     */
    public static final int DIFF_VIEW_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ViewMode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ViewMode forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_VIEW_MODE;
        case 1: return NEW;
        case 2: return PREVIOUS;
        case 3: return SPLIT_VIEW;
        case 4: return DIFF_VIEW;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ViewMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ViewMode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ViewMode>() {
            public ViewMode findValueByNumber(int number) {
              return ViewMode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.getDescriptor().getEnumTypes().get(0);
    }

    private static final ViewMode[] VALUES = values();

    public static ViewMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ViewMode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android_studio.RenderDiffViewerEvent.ViewMode)
  }

  private int bitField0_;
  public static final int VIEW_MODE_FIELD_NUMBER = 1;
  private int viewMode_ = 0;
  /**
   * <pre>
   * The comparison mode the user selected or is currently viewing.
   * </pre>
   *
   * <code>optional .android_studio.RenderDiffViewerEvent.ViewMode view_mode = 1;</code>
   * @return Whether the viewMode field is set.
   */
  @java.lang.Override public boolean hasViewMode() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The comparison mode the user selected or is currently viewing.
   * </pre>
   *
   * <code>optional .android_studio.RenderDiffViewerEvent.ViewMode view_mode = 1;</code>
   * @return The viewMode.
   */
  @java.lang.Override public com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.ViewMode getViewMode() {
    com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.ViewMode result = com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.ViewMode.forNumber(viewMode_);
    return result == null ? com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.ViewMode.UNKNOWN_VIEW_MODE : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, viewMode_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, viewMode_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.wireless.android.sdk.stats.RenderDiffViewerEvent)) {
      return super.equals(obj);
    }
    com.google.wireless.android.sdk.stats.RenderDiffViewerEvent other = (com.google.wireless.android.sdk.stats.RenderDiffViewerEvent) obj;

    if (hasViewMode() != other.hasViewMode()) return false;
    if (hasViewMode()) {
      if (viewMode_ != other.viewMode_) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasViewMode()) {
      hash = (37 * hash) + VIEW_MODE_FIELD_NUMBER;
      hash = (53 * hash) + viewMode_;
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.wireless.android.sdk.stats.RenderDiffViewerEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.RenderDiffViewerEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.RenderDiffViewerEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.RenderDiffViewerEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.RenderDiffViewerEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.RenderDiffViewerEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.RenderDiffViewerEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.RenderDiffViewerEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.RenderDiffViewerEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.RenderDiffViewerEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.RenderDiffViewerEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.RenderDiffViewerEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.RenderDiffViewerEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * Logged whenever the Visual Diff Viewer is displayed or when the user
   * switches between comparison modes (tabs).
   * </pre>
   *
   * Protobuf type {@code android_studio.RenderDiffViewerEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:android_studio.RenderDiffViewerEvent)
      com.google.wireless.android.sdk.stats.RenderDiffViewerEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_RenderDiffViewerEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_RenderDiffViewerEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.class, com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      viewMode_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_RenderDiffViewerEvent_descriptor;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.RenderDiffViewerEvent getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.RenderDiffViewerEvent build() {
      com.google.wireless.android.sdk.stats.RenderDiffViewerEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.RenderDiffViewerEvent buildPartial() {
      com.google.wireless.android.sdk.stats.RenderDiffViewerEvent result = new com.google.wireless.android.sdk.stats.RenderDiffViewerEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.wireless.android.sdk.stats.RenderDiffViewerEvent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.viewMode_ = viewMode_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.RenderDiffViewerEvent) {
        return mergeFrom((com.google.wireless.android.sdk.stats.RenderDiffViewerEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.RenderDiffViewerEvent other) {
      if (other == com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.getDefaultInstance()) return this;
      if (other.hasViewMode()) {
        setViewMode(other.getViewMode());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int tmpRaw = input.readEnum();
              com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.ViewMode tmpValue =
                  com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.ViewMode.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(1, tmpRaw);
              } else {
                viewMode_ = tmpRaw;
                bitField0_ |= 0x00000001;
              }
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int viewMode_ = 0;
    /**
     * <pre>
     * The comparison mode the user selected or is currently viewing.
     * </pre>
     *
     * <code>optional .android_studio.RenderDiffViewerEvent.ViewMode view_mode = 1;</code>
     * @return Whether the viewMode field is set.
     */
    @java.lang.Override public boolean hasViewMode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The comparison mode the user selected or is currently viewing.
     * </pre>
     *
     * <code>optional .android_studio.RenderDiffViewerEvent.ViewMode view_mode = 1;</code>
     * @return The viewMode.
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.ViewMode getViewMode() {
      com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.ViewMode result = com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.ViewMode.forNumber(viewMode_);
      return result == null ? com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.ViewMode.UNKNOWN_VIEW_MODE : result;
    }
    /**
     * <pre>
     * The comparison mode the user selected or is currently viewing.
     * </pre>
     *
     * <code>optional .android_studio.RenderDiffViewerEvent.ViewMode view_mode = 1;</code>
     * @param value The viewMode to set.
     * @return This builder for chaining.
     */
    public Builder setViewMode(com.google.wireless.android.sdk.stats.RenderDiffViewerEvent.ViewMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      viewMode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The comparison mode the user selected or is currently viewing.
     * </pre>
     *
     * <code>optional .android_studio.RenderDiffViewerEvent.ViewMode view_mode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearViewMode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      viewMode_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:android_studio.RenderDiffViewerEvent)
  }

  // @@protoc_insertion_point(class_scope:android_studio.RenderDiffViewerEvent)
  private static final com.google.wireless.android.sdk.stats.RenderDiffViewerEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.wireless.android.sdk.stats.RenderDiffViewerEvent();
  }

  public static com.google.wireless.android.sdk.stats.RenderDiffViewerEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<RenderDiffViewerEvent>
      PARSER = new com.google.protobuf.AbstractParser<RenderDiffViewerEvent>() {
    @java.lang.Override
    public RenderDiffViewerEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RenderDiffViewerEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RenderDiffViewerEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.wireless.android.sdk.stats.RenderDiffViewerEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

