// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface RollbackToolCallEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.RollbackToolCallEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The outcome of the event.
   * </pre>
   *
   * <code>optional .android_studio.RollbackToolCallEvent.RollbackOutcome outcome = 1;</code>
   * @return Whether the outcome field is set.
   */
  boolean hasOutcome();
  /**
   * <pre>
   * The outcome of the event.
   * </pre>
   *
   * <code>optional .android_studio.RollbackToolCallEvent.RollbackOutcome outcome = 1;</code>
   * @return The outcome.
   */
  com.google.wireless.android.sdk.stats.RollbackToolCallEvent.RollbackOutcome getOutcome();

  /**
   * <pre>
   * Specific failure reason if outcome is FAILED.
   * </pre>
   *
   * <code>optional .android_studio.RollbackToolCallEvent.FailureReason failure_reason = 3;</code>
   * @return Whether the failureReason field is set.
   */
  boolean hasFailureReason();
  /**
   * <pre>
   * Specific failure reason if outcome is FAILED.
   * </pre>
   *
   * <code>optional .android_studio.RollbackToolCallEvent.FailureReason failure_reason = 3;</code>
   * @return The failureReason.
   */
  com.google.wireless.android.sdk.stats.RollbackToolCallEvent.FailureReason getFailureReason();
}
