// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface SmlRagEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.SmlRagEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.android_studio.SmlRagEvent.RagIndexerMetrics rag_index = 1 [lazy = true];</code>
   * @return Whether the ragIndex field is set.
   */
  boolean hasRagIndex();
  /**
   * <code>.android_studio.SmlRagEvent.RagIndexerMetrics rag_index = 1 [lazy = true];</code>
   * @return The ragIndex.
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.RagIndexerMetrics getRagIndex();
  /**
   * <code>.android_studio.SmlRagEvent.RagIndexerMetrics rag_index = 1 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.RagIndexerMetricsOrBuilder getRagIndexOrBuilder();

  /**
   * <code>.android_studio.SmlRagEvent.RagToolMetrics rag_tool = 2 [lazy = true];</code>
   * @return Whether the ragTool field is set.
   */
  boolean hasRagTool();
  /**
   * <code>.android_studio.SmlRagEvent.RagToolMetrics rag_tool = 2 [lazy = true];</code>
   * @return The ragTool.
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.RagToolMetrics getRagTool();
  /**
   * <code>.android_studio.SmlRagEvent.RagToolMetrics rag_tool = 2 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.RagToolMetricsOrBuilder getRagToolOrBuilder();

  /**
   * <code>.android_studio.SmlRagEvent.FindFileMetrics find_file = 3 [lazy = true];</code>
   * @return Whether the findFile field is set.
   */
  boolean hasFindFile();
  /**
   * <code>.android_studio.SmlRagEvent.FindFileMetrics find_file = 3 [lazy = true];</code>
   * @return The findFile.
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.FindFileMetrics getFindFile();
  /**
   * <code>.android_studio.SmlRagEvent.FindFileMetrics find_file = 3 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.FindFileMetricsOrBuilder getFindFileOrBuilder();

  /**
   * <code>.android_studio.SmlRagEvent.GrepMetrics grep = 4 [lazy = true];</code>
   * @return Whether the grep field is set.
   */
  boolean hasGrep();
  /**
   * <code>.android_studio.SmlRagEvent.GrepMetrics grep = 4 [lazy = true];</code>
   * @return The grep.
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.GrepMetrics getGrep();
  /**
   * <code>.android_studio.SmlRagEvent.GrepMetrics grep = 4 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.GrepMetricsOrBuilder getGrepOrBuilder();

  /**
   * <code>.android_studio.SmlRagEvent.KbRagIndexerMetrics kb_rag = 5 [lazy = true];</code>
   * @return Whether the kbRag field is set.
   */
  boolean hasKbRag();
  /**
   * <code>.android_studio.SmlRagEvent.KbRagIndexerMetrics kb_rag = 5 [lazy = true];</code>
   * @return The kbRag.
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.KbRagIndexerMetrics getKbRag();
  /**
   * <code>.android_studio.SmlRagEvent.KbRagIndexerMetrics kb_rag = 5 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.KbRagIndexerMetricsOrBuilder getKbRagOrBuilder();

  /**
   * <code>.android_studio.SmlRagEvent.FindDeclarationMetrics find_declaration = 6 [lazy = true];</code>
   * @return Whether the findDeclaration field is set.
   */
  boolean hasFindDeclaration();
  /**
   * <code>.android_studio.SmlRagEvent.FindDeclarationMetrics find_declaration = 6 [lazy = true];</code>
   * @return The findDeclaration.
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.FindDeclarationMetrics getFindDeclaration();
  /**
   * <code>.android_studio.SmlRagEvent.FindDeclarationMetrics find_declaration = 6 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.FindDeclarationMetricsOrBuilder getFindDeclarationOrBuilder();

  /**
   * <code>.android_studio.SmlRagEvent.FindUsagesMetrics find_usages = 7 [lazy = true];</code>
   * @return Whether the findUsages field is set.
   */
  boolean hasFindUsages();
  /**
   * <code>.android_studio.SmlRagEvent.FindUsagesMetrics find_usages = 7 [lazy = true];</code>
   * @return The findUsages.
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.FindUsagesMetrics getFindUsages();
  /**
   * <code>.android_studio.SmlRagEvent.FindUsagesMetrics find_usages = 7 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.FindUsagesMetricsOrBuilder getFindUsagesOrBuilder();

  /**
   * <code>.android_studio.SmlRagEvent.LuceneIndexMetrics lucene_metrics = 8 [lazy = true];</code>
   * @return Whether the luceneMetrics field is set.
   */
  boolean hasLuceneMetrics();
  /**
   * <code>.android_studio.SmlRagEvent.LuceneIndexMetrics lucene_metrics = 8 [lazy = true];</code>
   * @return The luceneMetrics.
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.LuceneIndexMetrics getLuceneMetrics();
  /**
   * <code>.android_studio.SmlRagEvent.LuceneIndexMetrics lucene_metrics = 8 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.LuceneIndexMetricsOrBuilder getLuceneMetricsOrBuilder();

  /**
   * <code>.android_studio.SmlRagEvent.IntellijScanMetrics intellij_scan = 9 [lazy = true];</code>
   * @return Whether the intellijScan field is set.
   */
  boolean hasIntellijScan();
  /**
   * <code>.android_studio.SmlRagEvent.IntellijScanMetrics intellij_scan = 9 [lazy = true];</code>
   * @return The intellijScan.
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.IntellijScanMetrics getIntellijScan();
  /**
   * <code>.android_studio.SmlRagEvent.IntellijScanMetrics intellij_scan = 9 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.IntellijScanMetricsOrBuilder getIntellijScanOrBuilder();

  /**
   * <code>.android_studio.SmlRagEvent.IntellijIndexMetrics intellij_index = 10 [lazy = true];</code>
   * @return Whether the intellijIndex field is set.
   */
  boolean hasIntellijIndex();
  /**
   * <code>.android_studio.SmlRagEvent.IntellijIndexMetrics intellij_index = 10 [lazy = true];</code>
   * @return The intellijIndex.
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.IntellijIndexMetrics getIntellijIndex();
  /**
   * <code>.android_studio.SmlRagEvent.IntellijIndexMetrics intellij_index = 10 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SmlRagEvent.IntellijIndexMetricsOrBuilder getIntellijIndexOrBuilder();

  com.google.wireless.android.sdk.stats.SmlRagEvent.ContentCase getContentCase();
}
