// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats_logged_in.proto

package com.google.wireless.android.sdk.stats;

/**
 * Protobuf type {@code android_studio.SmlResponseMetadataLoggedIn}
 */
public final class SmlResponseMetadataLoggedIn extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:android_studio.SmlResponseMetadataLoggedIn)
    SmlResponseMetadataLoggedInOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SmlResponseMetadataLoggedIn.newBuilder() to construct.
  private SmlResponseMetadataLoggedIn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SmlResponseMetadataLoggedIn() {
    modelProviderId_ = "";
    modelId_ = "";
    agentType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SmlResponseMetadataLoggedIn();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStatsLoggedIn.internal_static_android_studio_SmlResponseMetadataLoggedIn_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStatsLoggedIn.internal_static_android_studio_SmlResponseMetadataLoggedIn_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.class, com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.Builder.class);
  }

  /**
   * <pre>
   * The type of agent used to generate an Sml response.
   * </pre>
   *
   * Protobuf enum {@code android_studio.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn}
   */
  public enum SmlAgentTypeLoggedIn
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>AGENT_TYPE_UNSPECIFIED = 0;</code>
     */
    AGENT_TYPE_UNSPECIFIED(0),
    /**
     * <code>AGENT_TYPE_GENERIC = 1;</code>
     */
    AGENT_TYPE_GENERIC(1),
    /**
     * <code>AGENT_TYPE_UPGRADE_AGENT = 2;</code>
     */
    AGENT_TYPE_UPGRADE_AGENT(2),
    /**
     * <code>AGENT_TYPE_NEW_PROJECT_AGENT = 3;</code>
     */
    AGENT_TYPE_NEW_PROJECT_AGENT(3),
    /**
     * <code>AGENT_TYPE_DEEP_LINK_LOGIC_AGENT = 4;</code>
     */
    AGENT_TYPE_DEEP_LINK_LOGIC_AGENT(4),
    ;

    /**
     * <code>AGENT_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int AGENT_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>AGENT_TYPE_GENERIC = 1;</code>
     */
    public static final int AGENT_TYPE_GENERIC_VALUE = 1;
    /**
     * <code>AGENT_TYPE_UPGRADE_AGENT = 2;</code>
     */
    public static final int AGENT_TYPE_UPGRADE_AGENT_VALUE = 2;
    /**
     * <code>AGENT_TYPE_NEW_PROJECT_AGENT = 3;</code>
     */
    public static final int AGENT_TYPE_NEW_PROJECT_AGENT_VALUE = 3;
    /**
     * <code>AGENT_TYPE_DEEP_LINK_LOGIC_AGENT = 4;</code>
     */
    public static final int AGENT_TYPE_DEEP_LINK_LOGIC_AGENT_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SmlAgentTypeLoggedIn valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SmlAgentTypeLoggedIn forNumber(int value) {
      switch (value) {
        case 0: return AGENT_TYPE_UNSPECIFIED;
        case 1: return AGENT_TYPE_GENERIC;
        case 2: return AGENT_TYPE_UPGRADE_AGENT;
        case 3: return AGENT_TYPE_NEW_PROJECT_AGENT;
        case 4: return AGENT_TYPE_DEEP_LINK_LOGIC_AGENT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SmlAgentTypeLoggedIn>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SmlAgentTypeLoggedIn> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SmlAgentTypeLoggedIn>() {
            public SmlAgentTypeLoggedIn findValueByNumber(int number) {
              return SmlAgentTypeLoggedIn.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.getDescriptor().getEnumTypes().get(0);
    }

    private static final SmlAgentTypeLoggedIn[] VALUES = values();

    public static SmlAgentTypeLoggedIn valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SmlAgentTypeLoggedIn(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android_studio.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn)
  }

  private int bitField0_;
  public static final int MODEL_PROVIDER_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object modelProviderId_ = "";
  /**
   * <pre>
   * e.g. google-aistudio, openai, or "default" for the built-in model
   * </pre>
   *
   * <code>optional string model_provider_id = 4;</code>
   * @return Whether the modelProviderId field is set.
   */
  @java.lang.Override
  public boolean hasModelProviderId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * e.g. google-aistudio, openai, or "default" for the built-in model
   * </pre>
   *
   * <code>optional string model_provider_id = 4;</code>
   * @return The modelProviderId.
   */
  @java.lang.Override
  public java.lang.String getModelProviderId() {
    java.lang.Object ref = modelProviderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        modelProviderId_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * e.g. google-aistudio, openai, or "default" for the built-in model
   * </pre>
   *
   * <code>optional string model_provider_id = 4;</code>
   * @return The bytes for modelProviderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelProviderIdBytes() {
    java.lang.Object ref = modelProviderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelProviderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_ID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object modelId_ = "";
  /**
   * <pre>
   * e.g. gemini-2.5-pro, o1, or "default" for the built-in model
   * </pre>
   *
   * <code>optional string model_id = 5;</code>
   * @return Whether the modelId field is set.
   */
  @java.lang.Override
  public boolean hasModelId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * e.g. gemini-2.5-pro, o1, or "default" for the built-in model
   * </pre>
   *
   * <code>optional string model_id = 5;</code>
   * @return The modelId.
   */
  @java.lang.Override
  public java.lang.String getModelId() {
    java.lang.Object ref = modelId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        modelId_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * e.g. gemini-2.5-pro, o1, or "default" for the built-in model
   * </pre>
   *
   * <code>optional string model_id = 5;</code>
   * @return The bytes for modelId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelIdBytes() {
    java.lang.Object ref = modelId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGENT_TYPE_FIELD_NUMBER = 7;
  private int agentType_ = 0;
  /**
   * <pre>
   * The type of the agent that generated the response.
   * </pre>
   *
   * <code>optional .android_studio.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn agent_type = 7;</code>
   * @return Whether the agentType field is set.
   */
  @java.lang.Override public boolean hasAgentType() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * The type of the agent that generated the response.
   * </pre>
   *
   * <code>optional .android_studio.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn agent_type = 7;</code>
   * @return The agentType.
   */
  @java.lang.Override public com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn getAgentType() {
    com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn result = com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn.forNumber(agentType_);
    return result == null ? com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn.AGENT_TYPE_UNSPECIFIED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, modelProviderId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, modelId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeEnum(7, agentType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, modelProviderId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, modelId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, agentType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn)) {
      return super.equals(obj);
    }
    com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn other = (com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn) obj;

    if (hasModelProviderId() != other.hasModelProviderId()) return false;
    if (hasModelProviderId()) {
      if (!getModelProviderId()
          .equals(other.getModelProviderId())) return false;
    }
    if (hasModelId() != other.hasModelId()) return false;
    if (hasModelId()) {
      if (!getModelId()
          .equals(other.getModelId())) return false;
    }
    if (hasAgentType() != other.hasAgentType()) return false;
    if (hasAgentType()) {
      if (agentType_ != other.agentType_) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasModelProviderId()) {
      hash = (37 * hash) + MODEL_PROVIDER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getModelProviderId().hashCode();
    }
    if (hasModelId()) {
      hash = (37 * hash) + MODEL_ID_FIELD_NUMBER;
      hash = (53 * hash) + getModelId().hashCode();
    }
    if (hasAgentType()) {
      hash = (37 * hash) + AGENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + agentType_;
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code android_studio.SmlResponseMetadataLoggedIn}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:android_studio.SmlResponseMetadataLoggedIn)
      com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedInOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStatsLoggedIn.internal_static_android_studio_SmlResponseMetadataLoggedIn_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStatsLoggedIn.internal_static_android_studio_SmlResponseMetadataLoggedIn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.class, com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      modelProviderId_ = "";
      modelId_ = "";
      agentType_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStatsLoggedIn.internal_static_android_studio_SmlResponseMetadataLoggedIn_descriptor;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn build() {
      com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn buildPartial() {
      com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn result = new com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.modelProviderId_ = modelProviderId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.modelId_ = modelId_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.agentType_ = agentType_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn) {
        return mergeFrom((com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn other) {
      if (other == com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.getDefaultInstance()) return this;
      if (other.hasModelProviderId()) {
        modelProviderId_ = other.modelProviderId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasModelId()) {
        modelId_ = other.modelId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasAgentType()) {
        setAgentType(other.getAgentType());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 34: {
              modelProviderId_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 34
            case 42: {
              modelId_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 42
            case 56: {
              int tmpRaw = input.readEnum();
              com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn tmpValue =
                  com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(7, tmpRaw);
              } else {
                agentType_ = tmpRaw;
                bitField0_ |= 0x00000004;
              }
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object modelProviderId_ = "";
    /**
     * <pre>
     * e.g. google-aistudio, openai, or "default" for the built-in model
     * </pre>
     *
     * <code>optional string model_provider_id = 4;</code>
     * @return Whether the modelProviderId field is set.
     */
    public boolean hasModelProviderId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * e.g. google-aistudio, openai, or "default" for the built-in model
     * </pre>
     *
     * <code>optional string model_provider_id = 4;</code>
     * @return The modelProviderId.
     */
    public java.lang.String getModelProviderId() {
      java.lang.Object ref = modelProviderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          modelProviderId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g. google-aistudio, openai, or "default" for the built-in model
     * </pre>
     *
     * <code>optional string model_provider_id = 4;</code>
     * @return The bytes for modelProviderId.
     */
    public com.google.protobuf.ByteString
        getModelProviderIdBytes() {
      java.lang.Object ref = modelProviderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelProviderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g. google-aistudio, openai, or "default" for the built-in model
     * </pre>
     *
     * <code>optional string model_provider_id = 4;</code>
     * @param value The modelProviderId to set.
     * @return This builder for chaining.
     */
    public Builder setModelProviderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      modelProviderId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. google-aistudio, openai, or "default" for the built-in model
     * </pre>
     *
     * <code>optional string model_provider_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearModelProviderId() {
      modelProviderId_ = getDefaultInstance().getModelProviderId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. google-aistudio, openai, or "default" for the built-in model
     * </pre>
     *
     * <code>optional string model_provider_id = 4;</code>
     * @param value The bytes for modelProviderId to set.
     * @return This builder for chaining.
     */
    public Builder setModelProviderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      modelProviderId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object modelId_ = "";
    /**
     * <pre>
     * e.g. gemini-2.5-pro, o1, or "default" for the built-in model
     * </pre>
     *
     * <code>optional string model_id = 5;</code>
     * @return Whether the modelId field is set.
     */
    public boolean hasModelId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * e.g. gemini-2.5-pro, o1, or "default" for the built-in model
     * </pre>
     *
     * <code>optional string model_id = 5;</code>
     * @return The modelId.
     */
    public java.lang.String getModelId() {
      java.lang.Object ref = modelId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          modelId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g. gemini-2.5-pro, o1, or "default" for the built-in model
     * </pre>
     *
     * <code>optional string model_id = 5;</code>
     * @return The bytes for modelId.
     */
    public com.google.protobuf.ByteString
        getModelIdBytes() {
      java.lang.Object ref = modelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g. gemini-2.5-pro, o1, or "default" for the built-in model
     * </pre>
     *
     * <code>optional string model_id = 5;</code>
     * @param value The modelId to set.
     * @return This builder for chaining.
     */
    public Builder setModelId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      modelId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. gemini-2.5-pro, o1, or "default" for the built-in model
     * </pre>
     *
     * <code>optional string model_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearModelId() {
      modelId_ = getDefaultInstance().getModelId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. gemini-2.5-pro, o1, or "default" for the built-in model
     * </pre>
     *
     * <code>optional string model_id = 5;</code>
     * @param value The bytes for modelId to set.
     * @return This builder for chaining.
     */
    public Builder setModelIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      modelId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int agentType_ = 0;
    /**
     * <pre>
     * The type of the agent that generated the response.
     * </pre>
     *
     * <code>optional .android_studio.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn agent_type = 7;</code>
     * @return Whether the agentType field is set.
     */
    @java.lang.Override public boolean hasAgentType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The type of the agent that generated the response.
     * </pre>
     *
     * <code>optional .android_studio.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn agent_type = 7;</code>
     * @return The agentType.
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn getAgentType() {
      com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn result = com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn.forNumber(agentType_);
      return result == null ? com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn.AGENT_TYPE_UNSPECIFIED : result;
    }
    /**
     * <pre>
     * The type of the agent that generated the response.
     * </pre>
     *
     * <code>optional .android_studio.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn agent_type = 7;</code>
     * @param value The agentType to set.
     * @return This builder for chaining.
     */
    public Builder setAgentType(com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      agentType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The type of the agent that generated the response.
     * </pre>
     *
     * <code>optional .android_studio.SmlResponseMetadataLoggedIn.SmlAgentTypeLoggedIn agent_type = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgentType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      agentType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:android_studio.SmlResponseMetadataLoggedIn)
  }

  // @@protoc_insertion_point(class_scope:android_studio.SmlResponseMetadataLoggedIn)
  private static final com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn();
  }

  public static com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<SmlResponseMetadataLoggedIn>
      PARSER = new com.google.protobuf.AbstractParser<SmlResponseMetadataLoggedIn>() {
    @java.lang.Override
    public SmlResponseMetadataLoggedIn parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SmlResponseMetadataLoggedIn> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SmlResponseMetadataLoggedIn> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.wireless.android.sdk.stats.SmlResponseMetadataLoggedIn getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

