// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kotlin_multiplatform_android_models.proto

package com.android.kotlin.multiplatform.models;

public final class KotlinMultiplatformAndroidModelsProto {
  private KotlinMultiplatformAndroidModelsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AndroidTarget_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AndroidTarget_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SourceProvider_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SourceProvider_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GeneratedSources_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GeneratedSources_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MainVariantInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MainVariantInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UnitTestInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UnitTestInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InstrumentedTestInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InstrumentedTestInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InstrumentedTestInfo_TestInstrumentationRunnerArgumentsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InstrumentedTestInfo_TestInstrumentationRunnerArgumentsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AndroidCompilation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AndroidCompilation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AndroidSourceSet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AndroidSourceSet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DependencyInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DependencyInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)kotlin_multiplatform_android_models.pr" +
      "oto\032\020ide_models.proto\"\374\005\n\rAndroidTarget\022" +
      "\030\n\013agp_version\030\001 \001(\tH\000\210\001\001\022\031\n\014project_pat" +
      "h\030\002 \001(\tH\001\210\001\001\022\035\n\tbuild_dir\030\003 \001(\0132\005.FileH\002" +
      "\210\001\001\022\035\n\016boot_classpath\030\004 \003(\0132\005.File\022!\n\tte" +
      "st_info\030\005 \001(\0132\t.TestInfoH\003\210\001\001\0224\n\005flags\030\006" +
      " \001(\0132 .AndroidGradlePluginProjectFlagsH\004" +
      "\210\001\001\022\037\n\020lint_checks_jars\030\007 \003(\0132\005.File\022/\n\"" +
      "is_core_library_desugaring_enabled\030\010 \001(\010" +
      "H\005\210\001\001\022!\n\022desugar_lib_config\030\t \003(\0132\005.File" +
      "\022\025\n\010group_id\030\n \001(\tH\006\210\001\001\022 \n\023build_tools_v" +
      "ersion\030\013 \001(\tH\007\210\001\001\022&\n\027desugared_methods_f" +
      "iles\030\014 \003(\0132\005.File\022!\n\rroot_build_id\030\r \001(\013" +
      "2\005.FileH\010\210\001\001\022\034\n\010build_id\030\016 \001(\0132\005.FileH\t\210" +
      "\001\001\022\026\n\twith_java\030\017 \001(\010H\n\210\001\001\022\034\n\017resource_p" +
      "refix\030\020 \001(\tH\013\210\001\001B\016\n\014_agp_versionB\017\n\r_pro" +
      "ject_pathB\014\n\n_build_dirB\014\n\n_test_infoB\010\n" +
      "\006_flagsB%\n#_is_core_library_desugaring_e" +
      "nabledB\013\n\t_group_idB\026\n\024_build_tools_vers" +
      "ionB\020\n\016_root_build_idB\013\n\t_build_idB\014\n\n_w" +
      "ith_javaB\022\n\020_resource_prefix\"E\n\016SourcePr" +
      "ovider\022!\n\rmanifest_file\030\001 \001(\0132\005.FileH\000\210\001" +
      "\001B\020\n\016_manifest_file\"1\n\020GeneratedSources\022" +
      "\035\n\016source_folders\030\001 \003(\0132\005.File\"\272\003\n\017MainV" +
      "ariantInfo\022\026\n\tnamespace\030\001 \001(\tH\000\210\001\001\022\037\n\022co" +
      "mpile_sdk_target\030\002 \001(\tH\001\210\001\001\022-\n\017min_sdk_v" +
      "ersion\030\003 \001(\0132\017.AndroidVersionH\002\210\001\001\022\034\n\017ma" +
      "x_sdk_version\030\004 \001(\005H\003\210\001\001\022\035\n\016proguard_fil" +
      "es\030\005 \003(\0132\005.File\022&\n\027consumer_proguard_fil" +
      "es\030\006 \003(\0132\005.File\022!\n\024minification_enabled\030" +
      "\007 \001(\010H\004\210\001\001\022&\n\027generated_asset_folders\030\010 " +
      "\003(\0132\005.File\022)\n\032generated_resource_folders" +
      "\030\t \003(\0132\005.FileB\014\n\n_namespaceB\025\n\023_compile_" +
      "sdk_targetB\022\n\020_min_sdk_versionB\022\n\020_max_s" +
      "dk_versionB\027\n\025_minification_enabled\"\263\001\n\014" +
      "UnitTestInfo\022\026\n\tnamespace\030\001 \001(\tH\000\210\001\001\022)\n\025" +
      "mockable_platform_jar\030\002 \001(\0132\005.FileH\001\210\001\001\022" +
      " \n\023unit_test_task_name\030\003 \001(\tH\002\210\001\001B\014\n\n_na" +
      "mespaceB\030\n\026_mockable_platform_jarB\026\n\024_un" +
      "it_test_task_name\"\257\004\n\024InstrumentedTestIn" +
      "fo\022\026\n\tnamespace\030\001 \001(\tH\000\210\001\001\022(\n\033test_instr" +
      "umentation_runner\030\002 \001(\tH\001\210\001\001\022l\n%test_ins" +
      "trumentation_runner_arguments\030\003 \003(\0132=.In" +
      "strumentedTestInfo.TestInstrumentationRu" +
      "nnerArgumentsEntry\022+\n\016signing_config\030\004 \001" +
      "(\0132\016.SigningConfigH\002\210\001\001\0225\n!assemble_task" +
      "_output_listing_file\030\005 \001(\0132\005.FileH\003\210\001\001\022&" +
      "\n\027generated_asset_folders\030\006 \003(\0132\005.File\022)" +
      "\n\032generated_resource_folders\030\007 \003(\0132\005.Fil" +
      "e\032I\n\'TestInstrumentationRunnerArgumentsE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\014\n\n" +
      "_namespaceB\036\n\034_test_instrumentation_runn" +
      "erB\021\n\017_signing_configB$\n\"_assemble_task_" +
      "output_listing_file\"\363\004\n\022AndroidCompilati" +
      "on\0226\n\004type\030\001 \001(\0162#.AndroidCompilation.Co" +
      "mpilationTypeH\000\210\001\001\022(\n\tmain_info\030\002 \001(\0132\020." +
      "MainVariantInfoH\001\210\001\001\022*\n\016unit_test_info\030\003" +
      " \001(\0132\r.UnitTestInfoH\002\210\001\001\022:\n\026instrumented" +
      "_test_info\030\004 \001(\0132\025.InstrumentedTestInfoH" +
      "\003\210\001\001\022$\n\027default_source_set_name\030\005 \001(\tH\004\210" +
      "\001\001\022\037\n\022assemble_task_name\030\006 \001(\tH\005\210\001\001\022%\n\030k" +
      "otlin_compile_task_name\030\007 \001(\tH\006\210\001\001\022$\n\025ex" +
      "tra_classes_folders\030\010 \003(\0132\005.File\022\'\n\030gene" +
      "rated_source_folders\030\t \003(\0132\005.File\"A\n\017Com" +
      "pilationType\022\010\n\004MAIN\020\000\022\r\n\tUNIT_TEST\020\001\022\025\n" +
      "\021INSTRUMENTED_TEST\020\002B\007\n\005_typeB\014\n\n_main_i" +
      "nfoB\021\n\017_unit_test_infoB\031\n\027_instrumented_" +
      "test_infoB\032\n\030_default_source_set_nameB\025\n" +
      "\023_assemble_task_nameB\033\n\031_kotlin_compile_" +
      "task_name\"U\n\020AndroidSourceSet\022-\n\017source_" +
      "provider\030\001 \001(\0132\017.SourceProviderH\000\210\001\001B\022\n\020" +
      "_source_provider\"<\n\016DependencyInfo\022\036\n\007li" +
      "brary\030\001 \001(\0132\010.LibraryH\000\210\001\001B\n\n\010_libraryBR" +
      "\n\'com.android.kotlin.multiplatform.model" +
      "sB%KotlinMultiplatformAndroidModelsProto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.android.builder.model.proto.ide.IdeModelsProto.getDescriptor(),
        });
    internal_static_AndroidTarget_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AndroidTarget_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AndroidTarget_descriptor,
        new java.lang.String[] { "AgpVersion", "ProjectPath", "BuildDir", "BootClasspath", "TestInfo", "Flags", "LintChecksJars", "IsCoreLibraryDesugaringEnabled", "DesugarLibConfig", "GroupId", "BuildToolsVersion", "DesugaredMethodsFiles", "RootBuildId", "BuildId", "WithJava", "ResourcePrefix", "AgpVersion", "ProjectPath", "BuildDir", "TestInfo", "Flags", "IsCoreLibraryDesugaringEnabled", "GroupId", "BuildToolsVersion", "RootBuildId", "BuildId", "WithJava", "ResourcePrefix", });
    internal_static_SourceProvider_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SourceProvider_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SourceProvider_descriptor,
        new java.lang.String[] { "ManifestFile", "ManifestFile", });
    internal_static_GeneratedSources_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GeneratedSources_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GeneratedSources_descriptor,
        new java.lang.String[] { "SourceFolders", });
    internal_static_MainVariantInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_MainVariantInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MainVariantInfo_descriptor,
        new java.lang.String[] { "Namespace", "CompileSdkTarget", "MinSdkVersion", "MaxSdkVersion", "ProguardFiles", "ConsumerProguardFiles", "MinificationEnabled", "GeneratedAssetFolders", "GeneratedResourceFolders", "Namespace", "CompileSdkTarget", "MinSdkVersion", "MaxSdkVersion", "MinificationEnabled", });
    internal_static_UnitTestInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_UnitTestInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UnitTestInfo_descriptor,
        new java.lang.String[] { "Namespace", "MockablePlatformJar", "UnitTestTaskName", "Namespace", "MockablePlatformJar", "UnitTestTaskName", });
    internal_static_InstrumentedTestInfo_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_InstrumentedTestInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InstrumentedTestInfo_descriptor,
        new java.lang.String[] { "Namespace", "TestInstrumentationRunner", "TestInstrumentationRunnerArguments", "SigningConfig", "AssembleTaskOutputListingFile", "GeneratedAssetFolders", "GeneratedResourceFolders", "Namespace", "TestInstrumentationRunner", "SigningConfig", "AssembleTaskOutputListingFile", });
    internal_static_InstrumentedTestInfo_TestInstrumentationRunnerArgumentsEntry_descriptor =
      internal_static_InstrumentedTestInfo_descriptor.getNestedTypes().get(0);
    internal_static_InstrumentedTestInfo_TestInstrumentationRunnerArgumentsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InstrumentedTestInfo_TestInstrumentationRunnerArgumentsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_AndroidCompilation_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_AndroidCompilation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AndroidCompilation_descriptor,
        new java.lang.String[] { "Type", "MainInfo", "UnitTestInfo", "InstrumentedTestInfo", "DefaultSourceSetName", "AssembleTaskName", "KotlinCompileTaskName", "ExtraClassesFolders", "GeneratedSourceFolders", "Type", "MainInfo", "UnitTestInfo", "InstrumentedTestInfo", "DefaultSourceSetName", "AssembleTaskName", "KotlinCompileTaskName", });
    internal_static_AndroidSourceSet_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_AndroidSourceSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AndroidSourceSet_descriptor,
        new java.lang.String[] { "SourceProvider", "SourceProvider", });
    internal_static_DependencyInfo_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_DependencyInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DependencyInfo_descriptor,
        new java.lang.String[] { "Library", "Library", });
    com.android.builder.model.proto.ide.IdeModelsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
