// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kotlin_multiplatform_android_models.proto

// Protobuf Java Version: 3.25.5
package com.android.kotlin.multiplatform.models;

/**
 * <pre>
 * Android sources of the component whose default kotlin sourceSet this is attached to.
 * </pre>
 *
 * Protobuf type {@code SourceProvider}
 */
public final class SourceProvider extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SourceProvider)
    SourceProviderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SourceProvider.newBuilder() to construct.
  private SourceProvider(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SourceProvider() {
    extraResDirectories_ = java.util.Collections.emptyList();
    extraAssetsDirectories_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SourceProvider();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.android.kotlin.multiplatform.models.KotlinMultiplatformAndroidModelsProto.internal_static_SourceProvider_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.android.kotlin.multiplatform.models.KotlinMultiplatformAndroidModelsProto.internal_static_SourceProvider_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.android.kotlin.multiplatform.models.SourceProvider.class, com.android.kotlin.multiplatform.models.SourceProvider.Builder.class);
  }

  private int bitField0_;
  public static final int MANIFEST_FILE_FIELD_NUMBER = 1;
  private com.android.builder.model.proto.ide.File manifestFile_;
  /**
   * <code>optional .File manifest_file = 1;</code>
   * @return Whether the manifestFile field is set.
   */
  @java.lang.Override
  public boolean hasManifestFile() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .File manifest_file = 1;</code>
   * @return The manifestFile.
   */
  @java.lang.Override
  public com.android.builder.model.proto.ide.File getManifestFile() {
    return manifestFile_ == null ? com.android.builder.model.proto.ide.File.getDefaultInstance() : manifestFile_;
  }
  /**
   * <code>optional .File manifest_file = 1;</code>
   */
  @java.lang.Override
  public com.android.builder.model.proto.ide.FileOrBuilder getManifestFileOrBuilder() {
    return manifestFile_ == null ? com.android.builder.model.proto.ide.File.getDefaultInstance() : manifestFile_;
  }

  public static final int EXTRA_RES_DIRECTORIES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.android.builder.model.proto.ide.File> extraResDirectories_;
  /**
   * <pre>
   * Non-generated res directories besides the default one, e.g. added with
   * `variant.sources.res.addStaticSourceDirectory()`.
   * </pre>
   *
   * <code>repeated .File extra_res_directories = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.android.builder.model.proto.ide.File> getExtraResDirectoriesList() {
    return extraResDirectories_;
  }
  /**
   * <pre>
   * Non-generated res directories besides the default one, e.g. added with
   * `variant.sources.res.addStaticSourceDirectory()`.
   * </pre>
   *
   * <code>repeated .File extra_res_directories = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.android.builder.model.proto.ide.FileOrBuilder> 
      getExtraResDirectoriesOrBuilderList() {
    return extraResDirectories_;
  }
  /**
   * <pre>
   * Non-generated res directories besides the default one, e.g. added with
   * `variant.sources.res.addStaticSourceDirectory()`.
   * </pre>
   *
   * <code>repeated .File extra_res_directories = 2;</code>
   */
  @java.lang.Override
  public int getExtraResDirectoriesCount() {
    return extraResDirectories_.size();
  }
  /**
   * <pre>
   * Non-generated res directories besides the default one, e.g. added with
   * `variant.sources.res.addStaticSourceDirectory()`.
   * </pre>
   *
   * <code>repeated .File extra_res_directories = 2;</code>
   */
  @java.lang.Override
  public com.android.builder.model.proto.ide.File getExtraResDirectories(int index) {
    return extraResDirectories_.get(index);
  }
  /**
   * <pre>
   * Non-generated res directories besides the default one, e.g. added with
   * `variant.sources.res.addStaticSourceDirectory()`.
   * </pre>
   *
   * <code>repeated .File extra_res_directories = 2;</code>
   */
  @java.lang.Override
  public com.android.builder.model.proto.ide.FileOrBuilder getExtraResDirectoriesOrBuilder(
      int index) {
    return extraResDirectories_.get(index);
  }

  public static final int EXTRA_ASSETS_DIRECTORIES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.android.builder.model.proto.ide.File> extraAssetsDirectories_;
  /**
   * <pre>
   * Non-generated assets directories besides the default one, e.g. added with
   * `variant.sources.assets.addStaticSourceDirectory()`.
   * </pre>
   *
   * <code>repeated .File extra_assets_directories = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.android.builder.model.proto.ide.File> getExtraAssetsDirectoriesList() {
    return extraAssetsDirectories_;
  }
  /**
   * <pre>
   * Non-generated assets directories besides the default one, e.g. added with
   * `variant.sources.assets.addStaticSourceDirectory()`.
   * </pre>
   *
   * <code>repeated .File extra_assets_directories = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.android.builder.model.proto.ide.FileOrBuilder> 
      getExtraAssetsDirectoriesOrBuilderList() {
    return extraAssetsDirectories_;
  }
  /**
   * <pre>
   * Non-generated assets directories besides the default one, e.g. added with
   * `variant.sources.assets.addStaticSourceDirectory()`.
   * </pre>
   *
   * <code>repeated .File extra_assets_directories = 3;</code>
   */
  @java.lang.Override
  public int getExtraAssetsDirectoriesCount() {
    return extraAssetsDirectories_.size();
  }
  /**
   * <pre>
   * Non-generated assets directories besides the default one, e.g. added with
   * `variant.sources.assets.addStaticSourceDirectory()`.
   * </pre>
   *
   * <code>repeated .File extra_assets_directories = 3;</code>
   */
  @java.lang.Override
  public com.android.builder.model.proto.ide.File getExtraAssetsDirectories(int index) {
    return extraAssetsDirectories_.get(index);
  }
  /**
   * <pre>
   * Non-generated assets directories besides the default one, e.g. added with
   * `variant.sources.assets.addStaticSourceDirectory()`.
   * </pre>
   *
   * <code>repeated .File extra_assets_directories = 3;</code>
   */
  @java.lang.Override
  public com.android.builder.model.proto.ide.FileOrBuilder getExtraAssetsDirectoriesOrBuilder(
      int index) {
    return extraAssetsDirectories_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getManifestFile());
    }
    for (int i = 0; i < extraResDirectories_.size(); i++) {
      output.writeMessage(2, extraResDirectories_.get(i));
    }
    for (int i = 0; i < extraAssetsDirectories_.size(); i++) {
      output.writeMessage(3, extraAssetsDirectories_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getManifestFile());
    }
    for (int i = 0; i < extraResDirectories_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, extraResDirectories_.get(i));
    }
    for (int i = 0; i < extraAssetsDirectories_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, extraAssetsDirectories_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.android.kotlin.multiplatform.models.SourceProvider)) {
      return super.equals(obj);
    }
    com.android.kotlin.multiplatform.models.SourceProvider other = (com.android.kotlin.multiplatform.models.SourceProvider) obj;

    if (hasManifestFile() != other.hasManifestFile()) return false;
    if (hasManifestFile()) {
      if (!getManifestFile()
          .equals(other.getManifestFile())) return false;
    }
    if (!getExtraResDirectoriesList()
        .equals(other.getExtraResDirectoriesList())) return false;
    if (!getExtraAssetsDirectoriesList()
        .equals(other.getExtraAssetsDirectoriesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasManifestFile()) {
      hash = (37 * hash) + MANIFEST_FILE_FIELD_NUMBER;
      hash = (53 * hash) + getManifestFile().hashCode();
    }
    if (getExtraResDirectoriesCount() > 0) {
      hash = (37 * hash) + EXTRA_RES_DIRECTORIES_FIELD_NUMBER;
      hash = (53 * hash) + getExtraResDirectoriesList().hashCode();
    }
    if (getExtraAssetsDirectoriesCount() > 0) {
      hash = (37 * hash) + EXTRA_ASSETS_DIRECTORIES_FIELD_NUMBER;
      hash = (53 * hash) + getExtraAssetsDirectoriesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.android.kotlin.multiplatform.models.SourceProvider parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.android.kotlin.multiplatform.models.SourceProvider parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.android.kotlin.multiplatform.models.SourceProvider parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.android.kotlin.multiplatform.models.SourceProvider parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.android.kotlin.multiplatform.models.SourceProvider parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.android.kotlin.multiplatform.models.SourceProvider parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.android.kotlin.multiplatform.models.SourceProvider parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.android.kotlin.multiplatform.models.SourceProvider parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.android.kotlin.multiplatform.models.SourceProvider parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.android.kotlin.multiplatform.models.SourceProvider parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.android.kotlin.multiplatform.models.SourceProvider parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.android.kotlin.multiplatform.models.SourceProvider parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.android.kotlin.multiplatform.models.SourceProvider prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Android sources of the component whose default kotlin sourceSet this is attached to.
   * </pre>
   *
   * Protobuf type {@code SourceProvider}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SourceProvider)
      com.android.kotlin.multiplatform.models.SourceProviderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.android.kotlin.multiplatform.models.KotlinMultiplatformAndroidModelsProto.internal_static_SourceProvider_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.android.kotlin.multiplatform.models.KotlinMultiplatformAndroidModelsProto.internal_static_SourceProvider_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.android.kotlin.multiplatform.models.SourceProvider.class, com.android.kotlin.multiplatform.models.SourceProvider.Builder.class);
    }

    // Construct using com.android.kotlin.multiplatform.models.SourceProvider.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getManifestFileFieldBuilder();
        getExtraResDirectoriesFieldBuilder();
        getExtraAssetsDirectoriesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      manifestFile_ = null;
      if (manifestFileBuilder_ != null) {
        manifestFileBuilder_.dispose();
        manifestFileBuilder_ = null;
      }
      if (extraResDirectoriesBuilder_ == null) {
        extraResDirectories_ = java.util.Collections.emptyList();
      } else {
        extraResDirectories_ = null;
        extraResDirectoriesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (extraAssetsDirectoriesBuilder_ == null) {
        extraAssetsDirectories_ = java.util.Collections.emptyList();
      } else {
        extraAssetsDirectories_ = null;
        extraAssetsDirectoriesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.android.kotlin.multiplatform.models.KotlinMultiplatformAndroidModelsProto.internal_static_SourceProvider_descriptor;
    }

    @java.lang.Override
    public com.android.kotlin.multiplatform.models.SourceProvider getDefaultInstanceForType() {
      return com.android.kotlin.multiplatform.models.SourceProvider.getDefaultInstance();
    }

    @java.lang.Override
    public com.android.kotlin.multiplatform.models.SourceProvider build() {
      com.android.kotlin.multiplatform.models.SourceProvider result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.android.kotlin.multiplatform.models.SourceProvider buildPartial() {
      com.android.kotlin.multiplatform.models.SourceProvider result = new com.android.kotlin.multiplatform.models.SourceProvider(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.android.kotlin.multiplatform.models.SourceProvider result) {
      if (extraResDirectoriesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          extraResDirectories_ = java.util.Collections.unmodifiableList(extraResDirectories_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.extraResDirectories_ = extraResDirectories_;
      } else {
        result.extraResDirectories_ = extraResDirectoriesBuilder_.build();
      }
      if (extraAssetsDirectoriesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          extraAssetsDirectories_ = java.util.Collections.unmodifiableList(extraAssetsDirectories_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.extraAssetsDirectories_ = extraAssetsDirectories_;
      } else {
        result.extraAssetsDirectories_ = extraAssetsDirectoriesBuilder_.build();
      }
    }

    private void buildPartial0(com.android.kotlin.multiplatform.models.SourceProvider result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.manifestFile_ = manifestFileBuilder_ == null
            ? manifestFile_
            : manifestFileBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.android.kotlin.multiplatform.models.SourceProvider) {
        return mergeFrom((com.android.kotlin.multiplatform.models.SourceProvider)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.android.kotlin.multiplatform.models.SourceProvider other) {
      if (other == com.android.kotlin.multiplatform.models.SourceProvider.getDefaultInstance()) return this;
      if (other.hasManifestFile()) {
        mergeManifestFile(other.getManifestFile());
      }
      if (extraResDirectoriesBuilder_ == null) {
        if (!other.extraResDirectories_.isEmpty()) {
          if (extraResDirectories_.isEmpty()) {
            extraResDirectories_ = other.extraResDirectories_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureExtraResDirectoriesIsMutable();
            extraResDirectories_.addAll(other.extraResDirectories_);
          }
          onChanged();
        }
      } else {
        if (!other.extraResDirectories_.isEmpty()) {
          if (extraResDirectoriesBuilder_.isEmpty()) {
            extraResDirectoriesBuilder_.dispose();
            extraResDirectoriesBuilder_ = null;
            extraResDirectories_ = other.extraResDirectories_;
            bitField0_ = (bitField0_ & ~0x00000002);
            extraResDirectoriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getExtraResDirectoriesFieldBuilder() : null;
          } else {
            extraResDirectoriesBuilder_.addAllMessages(other.extraResDirectories_);
          }
        }
      }
      if (extraAssetsDirectoriesBuilder_ == null) {
        if (!other.extraAssetsDirectories_.isEmpty()) {
          if (extraAssetsDirectories_.isEmpty()) {
            extraAssetsDirectories_ = other.extraAssetsDirectories_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureExtraAssetsDirectoriesIsMutable();
            extraAssetsDirectories_.addAll(other.extraAssetsDirectories_);
          }
          onChanged();
        }
      } else {
        if (!other.extraAssetsDirectories_.isEmpty()) {
          if (extraAssetsDirectoriesBuilder_.isEmpty()) {
            extraAssetsDirectoriesBuilder_.dispose();
            extraAssetsDirectoriesBuilder_ = null;
            extraAssetsDirectories_ = other.extraAssetsDirectories_;
            bitField0_ = (bitField0_ & ~0x00000004);
            extraAssetsDirectoriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getExtraAssetsDirectoriesFieldBuilder() : null;
          } else {
            extraAssetsDirectoriesBuilder_.addAllMessages(other.extraAssetsDirectories_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getManifestFileFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.android.builder.model.proto.ide.File m =
                  input.readMessage(
                      com.android.builder.model.proto.ide.File.parser(),
                      extensionRegistry);
              if (extraResDirectoriesBuilder_ == null) {
                ensureExtraResDirectoriesIsMutable();
                extraResDirectories_.add(m);
              } else {
                extraResDirectoriesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              com.android.builder.model.proto.ide.File m =
                  input.readMessage(
                      com.android.builder.model.proto.ide.File.parser(),
                      extensionRegistry);
              if (extraAssetsDirectoriesBuilder_ == null) {
                ensureExtraAssetsDirectoriesIsMutable();
                extraAssetsDirectories_.add(m);
              } else {
                extraAssetsDirectoriesBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.android.builder.model.proto.ide.File manifestFile_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.android.builder.model.proto.ide.File, com.android.builder.model.proto.ide.File.Builder, com.android.builder.model.proto.ide.FileOrBuilder> manifestFileBuilder_;
    /**
     * <code>optional .File manifest_file = 1;</code>
     * @return Whether the manifestFile field is set.
     */
    public boolean hasManifestFile() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .File manifest_file = 1;</code>
     * @return The manifestFile.
     */
    public com.android.builder.model.proto.ide.File getManifestFile() {
      if (manifestFileBuilder_ == null) {
        return manifestFile_ == null ? com.android.builder.model.proto.ide.File.getDefaultInstance() : manifestFile_;
      } else {
        return manifestFileBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .File manifest_file = 1;</code>
     */
    public Builder setManifestFile(com.android.builder.model.proto.ide.File value) {
      if (manifestFileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        manifestFile_ = value;
      } else {
        manifestFileBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .File manifest_file = 1;</code>
     */
    public Builder setManifestFile(
        com.android.builder.model.proto.ide.File.Builder builderForValue) {
      if (manifestFileBuilder_ == null) {
        manifestFile_ = builderForValue.build();
      } else {
        manifestFileBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .File manifest_file = 1;</code>
     */
    public Builder mergeManifestFile(com.android.builder.model.proto.ide.File value) {
      if (manifestFileBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          manifestFile_ != null &&
          manifestFile_ != com.android.builder.model.proto.ide.File.getDefaultInstance()) {
          getManifestFileBuilder().mergeFrom(value);
        } else {
          manifestFile_ = value;
        }
      } else {
        manifestFileBuilder_.mergeFrom(value);
      }
      if (manifestFile_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .File manifest_file = 1;</code>
     */
    public Builder clearManifestFile() {
      bitField0_ = (bitField0_ & ~0x00000001);
      manifestFile_ = null;
      if (manifestFileBuilder_ != null) {
        manifestFileBuilder_.dispose();
        manifestFileBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .File manifest_file = 1;</code>
     */
    public com.android.builder.model.proto.ide.File.Builder getManifestFileBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getManifestFileFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .File manifest_file = 1;</code>
     */
    public com.android.builder.model.proto.ide.FileOrBuilder getManifestFileOrBuilder() {
      if (manifestFileBuilder_ != null) {
        return manifestFileBuilder_.getMessageOrBuilder();
      } else {
        return manifestFile_ == null ?
            com.android.builder.model.proto.ide.File.getDefaultInstance() : manifestFile_;
      }
    }
    /**
     * <code>optional .File manifest_file = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.android.builder.model.proto.ide.File, com.android.builder.model.proto.ide.File.Builder, com.android.builder.model.proto.ide.FileOrBuilder> 
        getManifestFileFieldBuilder() {
      if (manifestFileBuilder_ == null) {
        manifestFileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.android.builder.model.proto.ide.File, com.android.builder.model.proto.ide.File.Builder, com.android.builder.model.proto.ide.FileOrBuilder>(
                getManifestFile(),
                getParentForChildren(),
                isClean());
        manifestFile_ = null;
      }
      return manifestFileBuilder_;
    }

    private java.util.List<com.android.builder.model.proto.ide.File> extraResDirectories_ =
      java.util.Collections.emptyList();
    private void ensureExtraResDirectoriesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        extraResDirectories_ = new java.util.ArrayList<com.android.builder.model.proto.ide.File>(extraResDirectories_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.android.builder.model.proto.ide.File, com.android.builder.model.proto.ide.File.Builder, com.android.builder.model.proto.ide.FileOrBuilder> extraResDirectoriesBuilder_;

    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public java.util.List<com.android.builder.model.proto.ide.File> getExtraResDirectoriesList() {
      if (extraResDirectoriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(extraResDirectories_);
      } else {
        return extraResDirectoriesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public int getExtraResDirectoriesCount() {
      if (extraResDirectoriesBuilder_ == null) {
        return extraResDirectories_.size();
      } else {
        return extraResDirectoriesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public com.android.builder.model.proto.ide.File getExtraResDirectories(int index) {
      if (extraResDirectoriesBuilder_ == null) {
        return extraResDirectories_.get(index);
      } else {
        return extraResDirectoriesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public Builder setExtraResDirectories(
        int index, com.android.builder.model.proto.ide.File value) {
      if (extraResDirectoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtraResDirectoriesIsMutable();
        extraResDirectories_.set(index, value);
        onChanged();
      } else {
        extraResDirectoriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public Builder setExtraResDirectories(
        int index, com.android.builder.model.proto.ide.File.Builder builderForValue) {
      if (extraResDirectoriesBuilder_ == null) {
        ensureExtraResDirectoriesIsMutable();
        extraResDirectories_.set(index, builderForValue.build());
        onChanged();
      } else {
        extraResDirectoriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public Builder addExtraResDirectories(com.android.builder.model.proto.ide.File value) {
      if (extraResDirectoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtraResDirectoriesIsMutable();
        extraResDirectories_.add(value);
        onChanged();
      } else {
        extraResDirectoriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public Builder addExtraResDirectories(
        int index, com.android.builder.model.proto.ide.File value) {
      if (extraResDirectoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtraResDirectoriesIsMutable();
        extraResDirectories_.add(index, value);
        onChanged();
      } else {
        extraResDirectoriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public Builder addExtraResDirectories(
        com.android.builder.model.proto.ide.File.Builder builderForValue) {
      if (extraResDirectoriesBuilder_ == null) {
        ensureExtraResDirectoriesIsMutable();
        extraResDirectories_.add(builderForValue.build());
        onChanged();
      } else {
        extraResDirectoriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public Builder addExtraResDirectories(
        int index, com.android.builder.model.proto.ide.File.Builder builderForValue) {
      if (extraResDirectoriesBuilder_ == null) {
        ensureExtraResDirectoriesIsMutable();
        extraResDirectories_.add(index, builderForValue.build());
        onChanged();
      } else {
        extraResDirectoriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public Builder addAllExtraResDirectories(
        java.lang.Iterable<? extends com.android.builder.model.proto.ide.File> values) {
      if (extraResDirectoriesBuilder_ == null) {
        ensureExtraResDirectoriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, extraResDirectories_);
        onChanged();
      } else {
        extraResDirectoriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public Builder clearExtraResDirectories() {
      if (extraResDirectoriesBuilder_ == null) {
        extraResDirectories_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        extraResDirectoriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public Builder removeExtraResDirectories(int index) {
      if (extraResDirectoriesBuilder_ == null) {
        ensureExtraResDirectoriesIsMutable();
        extraResDirectories_.remove(index);
        onChanged();
      } else {
        extraResDirectoriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public com.android.builder.model.proto.ide.File.Builder getExtraResDirectoriesBuilder(
        int index) {
      return getExtraResDirectoriesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public com.android.builder.model.proto.ide.FileOrBuilder getExtraResDirectoriesOrBuilder(
        int index) {
      if (extraResDirectoriesBuilder_ == null) {
        return extraResDirectories_.get(index);  } else {
        return extraResDirectoriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public java.util.List<? extends com.android.builder.model.proto.ide.FileOrBuilder> 
         getExtraResDirectoriesOrBuilderList() {
      if (extraResDirectoriesBuilder_ != null) {
        return extraResDirectoriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(extraResDirectories_);
      }
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public com.android.builder.model.proto.ide.File.Builder addExtraResDirectoriesBuilder() {
      return getExtraResDirectoriesFieldBuilder().addBuilder(
          com.android.builder.model.proto.ide.File.getDefaultInstance());
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public com.android.builder.model.proto.ide.File.Builder addExtraResDirectoriesBuilder(
        int index) {
      return getExtraResDirectoriesFieldBuilder().addBuilder(
          index, com.android.builder.model.proto.ide.File.getDefaultInstance());
    }
    /**
     * <pre>
     * Non-generated res directories besides the default one, e.g. added with
     * `variant.sources.res.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_res_directories = 2;</code>
     */
    public java.util.List<com.android.builder.model.proto.ide.File.Builder> 
         getExtraResDirectoriesBuilderList() {
      return getExtraResDirectoriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.android.builder.model.proto.ide.File, com.android.builder.model.proto.ide.File.Builder, com.android.builder.model.proto.ide.FileOrBuilder> 
        getExtraResDirectoriesFieldBuilder() {
      if (extraResDirectoriesBuilder_ == null) {
        extraResDirectoriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.android.builder.model.proto.ide.File, com.android.builder.model.proto.ide.File.Builder, com.android.builder.model.proto.ide.FileOrBuilder>(
                extraResDirectories_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        extraResDirectories_ = null;
      }
      return extraResDirectoriesBuilder_;
    }

    private java.util.List<com.android.builder.model.proto.ide.File> extraAssetsDirectories_ =
      java.util.Collections.emptyList();
    private void ensureExtraAssetsDirectoriesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        extraAssetsDirectories_ = new java.util.ArrayList<com.android.builder.model.proto.ide.File>(extraAssetsDirectories_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.android.builder.model.proto.ide.File, com.android.builder.model.proto.ide.File.Builder, com.android.builder.model.proto.ide.FileOrBuilder> extraAssetsDirectoriesBuilder_;

    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public java.util.List<com.android.builder.model.proto.ide.File> getExtraAssetsDirectoriesList() {
      if (extraAssetsDirectoriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(extraAssetsDirectories_);
      } else {
        return extraAssetsDirectoriesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public int getExtraAssetsDirectoriesCount() {
      if (extraAssetsDirectoriesBuilder_ == null) {
        return extraAssetsDirectories_.size();
      } else {
        return extraAssetsDirectoriesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public com.android.builder.model.proto.ide.File getExtraAssetsDirectories(int index) {
      if (extraAssetsDirectoriesBuilder_ == null) {
        return extraAssetsDirectories_.get(index);
      } else {
        return extraAssetsDirectoriesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public Builder setExtraAssetsDirectories(
        int index, com.android.builder.model.proto.ide.File value) {
      if (extraAssetsDirectoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtraAssetsDirectoriesIsMutable();
        extraAssetsDirectories_.set(index, value);
        onChanged();
      } else {
        extraAssetsDirectoriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public Builder setExtraAssetsDirectories(
        int index, com.android.builder.model.proto.ide.File.Builder builderForValue) {
      if (extraAssetsDirectoriesBuilder_ == null) {
        ensureExtraAssetsDirectoriesIsMutable();
        extraAssetsDirectories_.set(index, builderForValue.build());
        onChanged();
      } else {
        extraAssetsDirectoriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public Builder addExtraAssetsDirectories(com.android.builder.model.proto.ide.File value) {
      if (extraAssetsDirectoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtraAssetsDirectoriesIsMutable();
        extraAssetsDirectories_.add(value);
        onChanged();
      } else {
        extraAssetsDirectoriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public Builder addExtraAssetsDirectories(
        int index, com.android.builder.model.proto.ide.File value) {
      if (extraAssetsDirectoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtraAssetsDirectoriesIsMutable();
        extraAssetsDirectories_.add(index, value);
        onChanged();
      } else {
        extraAssetsDirectoriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public Builder addExtraAssetsDirectories(
        com.android.builder.model.proto.ide.File.Builder builderForValue) {
      if (extraAssetsDirectoriesBuilder_ == null) {
        ensureExtraAssetsDirectoriesIsMutable();
        extraAssetsDirectories_.add(builderForValue.build());
        onChanged();
      } else {
        extraAssetsDirectoriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public Builder addExtraAssetsDirectories(
        int index, com.android.builder.model.proto.ide.File.Builder builderForValue) {
      if (extraAssetsDirectoriesBuilder_ == null) {
        ensureExtraAssetsDirectoriesIsMutable();
        extraAssetsDirectories_.add(index, builderForValue.build());
        onChanged();
      } else {
        extraAssetsDirectoriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public Builder addAllExtraAssetsDirectories(
        java.lang.Iterable<? extends com.android.builder.model.proto.ide.File> values) {
      if (extraAssetsDirectoriesBuilder_ == null) {
        ensureExtraAssetsDirectoriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, extraAssetsDirectories_);
        onChanged();
      } else {
        extraAssetsDirectoriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public Builder clearExtraAssetsDirectories() {
      if (extraAssetsDirectoriesBuilder_ == null) {
        extraAssetsDirectories_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        extraAssetsDirectoriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public Builder removeExtraAssetsDirectories(int index) {
      if (extraAssetsDirectoriesBuilder_ == null) {
        ensureExtraAssetsDirectoriesIsMutable();
        extraAssetsDirectories_.remove(index);
        onChanged();
      } else {
        extraAssetsDirectoriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public com.android.builder.model.proto.ide.File.Builder getExtraAssetsDirectoriesBuilder(
        int index) {
      return getExtraAssetsDirectoriesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public com.android.builder.model.proto.ide.FileOrBuilder getExtraAssetsDirectoriesOrBuilder(
        int index) {
      if (extraAssetsDirectoriesBuilder_ == null) {
        return extraAssetsDirectories_.get(index);  } else {
        return extraAssetsDirectoriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public java.util.List<? extends com.android.builder.model.proto.ide.FileOrBuilder> 
         getExtraAssetsDirectoriesOrBuilderList() {
      if (extraAssetsDirectoriesBuilder_ != null) {
        return extraAssetsDirectoriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(extraAssetsDirectories_);
      }
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public com.android.builder.model.proto.ide.File.Builder addExtraAssetsDirectoriesBuilder() {
      return getExtraAssetsDirectoriesFieldBuilder().addBuilder(
          com.android.builder.model.proto.ide.File.getDefaultInstance());
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public com.android.builder.model.proto.ide.File.Builder addExtraAssetsDirectoriesBuilder(
        int index) {
      return getExtraAssetsDirectoriesFieldBuilder().addBuilder(
          index, com.android.builder.model.proto.ide.File.getDefaultInstance());
    }
    /**
     * <pre>
     * Non-generated assets directories besides the default one, e.g. added with
     * `variant.sources.assets.addStaticSourceDirectory()`.
     * </pre>
     *
     * <code>repeated .File extra_assets_directories = 3;</code>
     */
    public java.util.List<com.android.builder.model.proto.ide.File.Builder> 
         getExtraAssetsDirectoriesBuilderList() {
      return getExtraAssetsDirectoriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.android.builder.model.proto.ide.File, com.android.builder.model.proto.ide.File.Builder, com.android.builder.model.proto.ide.FileOrBuilder> 
        getExtraAssetsDirectoriesFieldBuilder() {
      if (extraAssetsDirectoriesBuilder_ == null) {
        extraAssetsDirectoriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.android.builder.model.proto.ide.File, com.android.builder.model.proto.ide.File.Builder, com.android.builder.model.proto.ide.FileOrBuilder>(
                extraAssetsDirectories_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        extraAssetsDirectories_ = null;
      }
      return extraAssetsDirectoriesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SourceProvider)
  }

  // @@protoc_insertion_point(class_scope:SourceProvider)
  private static final com.android.kotlin.multiplatform.models.SourceProvider DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.android.kotlin.multiplatform.models.SourceProvider();
  }

  public static com.android.kotlin.multiplatform.models.SourceProvider getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SourceProvider>
      PARSER = new com.google.protobuf.AbstractParser<SourceProvider>() {
    @java.lang.Override
    public SourceProvider parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SourceProvider> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SourceProvider> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.android.kotlin.multiplatform.models.SourceProvider getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

